### ISSUE TITLE
(docs) Update documentation targeting TestFX 4.0.

### ISSUE THREAD

**Issue by hastebrot** [TestFX/TestFX#138]
The documentation really needs some updates, clarification and extension.
### Outline

Basics:
- [ ] **Getting Started:** Download, Install, Compile, Execute

Concepts:
- [ ] **Framework** (Setup, Cleanup): Launch an Application or Stages within JUnit.
- [ ] **Robots** (Given, When): Simulate user interaction of mouse and keyboard.
- [ ] **Matchers** (Then): Verify the state of ui components.

**Comment by JordanMartinez** [comment]
@brcolow I plan on documenting the `matcher` package next. We still need to document `FxAssert`, but its method signatures need to be refined. Do you know what needs to be done before they are refined?

**Comment by brcolow** [comment]
I do not. Ping @hastebrot

**Comment by JordanMartinez** [comment]
While we may be missing documentation, I think much can be gathered from looking at examples. Is there a page to which we'd like to direct people that shows a lot of examples of other projects using this to test their JavaFX-related project to help such people get started?

For example, I wrote a number of tests for [RichTextFX here](https://github.com/TomasMikula/RichTextFX/tree/master/richtextfx/src/integrationTest/java/org/fxmisc/richtext).

**Comment by brcolow** [comment]
They should be posted on the wiki (for anyone reading this in the future).

Closing this issue as it is already known that our documentation needs a lot of work.
