### ISSUE TITLE
Add support for propagating uncaught exceptions that occur on the JavaFX Application Thread.

### ISSUE THREAD

**Issue by ryanjaeb** [TestFX/TestFX#155]
I started this as a discussion on the mailing list, but decided to add it here so I can consolidate the info and use some decent syntax highlighting for my feedback.

I would like to be able to have tests that fail if an uncaught exception occurs on the `JavaFX Application Thread`.  As a use case, I have the following example:

**NOTE**: This example must be run with JDK 8u20 since the issue is fixed in 8u40.

https://gist.github.com/ryanjaeb/4443d21c926ffbbc9f8c
https://javafx-jira.kenai.com/browse/RT-38888

Based on the mailing list discussion here is a complete example that will accomplish what I've asked for (created by Benjamin - thanks!).

https://gist.github.com/hastebrot/6c46ca56b64c2918b635

I would make the following minor changes to the example:

``` java
// Removed and replaced with local variable in the
// registerCustomExceptionHandler().  This borders on personal
// preference for code style - a very minor nitpick.
//private UncaughtExceptionHandler propagatorExceptionHandler;

private void registerCustomExceptionHandler() {
    // This can end up being null, so a null check has been added below.
    previousExceptionHandler = Thread.getDefaultUncaughtExceptionHandler();

    Thread.setDefaultUncaughtExceptionHandler((thread, throwable) -> {
        if(isFxUserThread(thread)) {
            thrownExceptions.add(throwable);
        }
        // Added a null check.
        else if(previousExceptionHandler != null) {
            previousExceptionHandler.uncaughtException(thread, throwable);
        }
    });
}
```

I'm quite satisfied with this approach, but there are a few things worth noting.
1. Using a JUnit `@Rule` may not port well once you want to add TestNG support.
2. JUnit makes some exception related assumptions that don't seem to play nice with propagating exceptions from the rule.  Specifically, it's not possible to use:

``` java
@Test(expected = NullPointerException.class)
```

...with the example.  The above expects the exception to be thrown from the test method, not the enclosing rule.

Would it be more practical to have `GuiTest` propagate exceptions instead of using a JUnit `@Rule`?  Would that make it easier to add TestNG support?  Personally, I like the `@Rule` approach.  It's only a few lines of code and it's easy to understand.

I spent some time looking for a TestNG feature similar to JUnit's `@Rule`, but didn't find anything.  Does anyone know if a similar feature exists in TestNG?  I did notice that TestNG is able to execute JUnit tests, which is something I hadn't realized before.

http://testng.org/doc/documentation-main.html#junit

**Comment by schubkatze** [comment]
Hi,

is there any support for this in current testfx now? 
If yes, how do I use it? 
Let's say I've got the following example application. 

Application:
```
public class HelloWorld extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Button button = new Button("hello");
        button.setOnAction(e -> {
            throw new RuntimeException("Something Went Wrong: Notice me");
        });
        StackPane root = new StackPane(button);

        Scene scene = new Scene(root, 200, 150);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Hello World");
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

Test:
```
@Test
public void test() {
    // ...
    clickOn("hello");	// ?
    // ...
}

```
How should my click-test look like, if I expect the test to fail and show that there's something wrong with my application?
Or should I use the proposed propagator(Rule)?

Thank you in advance.

**Comment by brcolow** [comment]
Take a look at [WaitForAsyncUtils.asyncFx(..)](https://github.com/TestFX/TestFX/blob/master/subprojects/testfx-core/src/main/java/org/testfx/util/WaitForAsyncUtils.java#L215)

**Comment by schubkatze** [comment]
Thank you for your quick response. I've already seen the class, but I don't know how to use it with interactions.

I tried something like this (and variations with async() and Callables), but I won't get any exceptions either. 
```
    @Test
    public void test() throws Throwable {
        Future<Void> fut = asyncFx(() ->  {clickOn("hello");});
        waitForFxEvents(100);
        fut.get(); //or checkException();
    }
```

The click will be simulated and WaitForAsyncUtils won't get the exception of the provoked upcall.
So I still don't know how to make my test look like. I like the idea of simulating the click and not invoking it with events directly.
I appreciate your help. Thank you.

**Comment by brcolow** [comment]
@Ortner Pinging you in on this because I tried to test for catching exceptions that were thrown on the JavaFX thread and am also not getting it to work. Take as an example a `Button`'s onAction handler throwing an exception as @schubkatze 's example uses:

```java
import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static org.hamcrest.Matchers.instanceOf;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.concurrent.Future;
import java.util.concurrent.TimeoutException;

import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;
import org.testfx.api.FxToolkit;
import org.testfx.framework.junit.ApplicationTest;
import org.testfx.util.WaitForAsyncUtils;

/**
 * @author Michael Ennen
 */
public class HelloWorldApplication extends ApplicationTest
{
    @Rule
    public ExpectedException thrown = ExpectedException.none();

    @Rule
    public Timeout globalTimeout = Timeout.millis(10000);

    @BeforeClass
    public static void setUpClass() {
        try {
            FxToolkit.registerPrimaryStage();
        }
        catch (TimeoutException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void start(Stage primaryStage)
    {
        Button button = new Button("hello");
        button.setOnAction(e -> {
            throw new UnsupportedOperationException("Something Went Wrong: Notice me");
        });
        StackPane root = new StackPane(button);

        Scene scene = new Scene(root, 200, 150);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Hello World");
        primaryStage.show();
    }

    @Test
    public void test2() throws Throwable
    {
        //given:
        WaitForAsyncUtils.printException = false;
        thrown.expectCause(instanceOf(UnsupportedOperationException.class));
        Runnable runnable = () -> clickOn("hello");
        WaitForAsyncUtils.clearExceptions();

        // when:
        Future<Void> future = WaitForAsyncUtils.asyncFx(runnable);
        while (!future.isDone()) {
            Thread.sleep(50);
        }
        assertTrue(future.isDone());

        // then:
        try {
            WaitForAsyncUtils.checkException();
            fail("checkException didn't detect Exception");
        }
        catch (Throwable e) {
            if (!(e instanceof UnsupportedOperationException)) {
                throw e;
            }
        }
        WaitForAsyncUtils.printException = true;
        WaitForAsyncUtils.waitFor(50, MILLISECONDS, future);
        waitForThreads(future);
    }

    protected void waitForThreads(Future<?> f) {
        while (!f.isDone()) {
            try {
                Thread.sleep(1);
            }
            catch (Exception ignore) {
            }
        }
        try {
            Thread.sleep(50);
        }
        catch (Exception ignore) {
        }
    }

}
```

This `test2` will fail because no exception is caught via `checkException`. I am pinging you, Ortner, as you are the author of the `WaitForAsyncUtils` stuff and I have never used it before but I thought I understood the general idea...am I using it incorrectly?

**Comment by Ortner** [comment]
I've had a first look at it. I suppose it's not actually a problem of the `WaitForAsyncUtils`.

This test works:
```java
package org.testfx.framework.junit;

import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static org.hamcrest.Matchers.instanceOf;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.concurrent.Future;
import java.util.concurrent.TimeoutException;

import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;
import org.testfx.api.FxToolkit;
import org.testfx.framework.junit.ApplicationTest;
import org.testfx.util.WaitForAsyncUtils;

public class ForwardBugTest155  extends ApplicationTest{
    @Rule
    public ExpectedException thrown = ExpectedException.none();

    @Rule
    public Timeout globalTimeout = Timeout.millis(10000);

    Button button = null;
    
    @BeforeClass
    public static void setUpClass() {
        try {
            FxToolkit.registerPrimaryStage();
        }
        catch (TimeoutException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void start(Stage primaryStage)
    {
        button = new Button("hello");
        button.setOnAction(e -> {
            throw new UnsupportedOperationException("Something Went Wrong: Notice me");
        });
        StackPane root = new StackPane(button);

        Scene scene = new Scene(root, 200, 150);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Hello World");
        primaryStage.show();
    }

    @Test
    public void test2() throws Throwable
    {
        //given:
        thrown.expectCause(instanceOf(UnsupportedOperationException.class));
        WaitForAsyncUtils.clearExceptions();
        
        WaitForAsyncUtils.waitForAsyncFx(1000, () -> button.fire());
        fail("checkException didn't detect Exception");
    }
}
```

The `WaitForAsyncUtils` do only forward the exceptions of the called methods. As the fire action of the button is called directly  (on the FX-Application-Thread) in this (modified) test, the exception is forwarded to the calling thread.

The problem of your test is the exception handling of the robot - I assume (didn't dig into it yet). I will have a look on the Robot code...

**Comment by Ortner** [comment]
The issue is, that the Robot puts the corresponding event in the event queue and doesn't even wait for it to finish per default (see `java.awt.Robot.afterEvent()` the wait parameters are 0 or false per default). The TestFX part is using the async methods to call the `AWTRobot` methods which calls the `Robot.mousePress` method with the button as argument (any deeper it becomes bytecode). As far as I understand the Event is pushed on the Dispatcher Thread and the FX-Application-Thread afterwards (not observed by `WaitForAsyncUtils` as the Event is executed, not the Callable created in TestFx).

So I don't see a way to fetch this Exception within the call hierarchy. The only way is to fetch all unhandled Exceptions. But this has some limitations:

- Exception Handling is always Asynchronous, so if not correctly checked the exception of a previous test may pop up in the next test
- No call hierarchy means no proper Stacktrace. So in the Button example it will point to the ActionHandler but not to line of the test where it was called. This is a useful feature especially regarding the issue above.

I will post a PR as proposal for this solution.

**Comment by brcolow** [comment]
@schubkatze https://github.com/TestFX/TestFX/pull/440 has been merged, this should take care of your use-case.
