### ISSUE TITLE
Change artifact name to "testfx"

### ISSUE THREAD

**Issue by johnzeringue** [TestFX/TestFX#182]
Currently `testCompile 'org.loadui:testfx:3.1.0'`causes a build error in Gradle due to the name of the TestFX Maven artifact being `testFx` (with a capital `F`).

It would be much easier to remember or guess if it were `testfx` instead. In fact, all lowercase seems to be the general convention for Maven artifacts. For example, despite usually branding itself as `JUnit`, the popular test framework is `junit` on Maven.

Of course, changing the name of the existing artifact could cause issues for current users. `testCompile 'org.loadui:testFx:+'`, for example, would no longer grab the latest version of TestFX, but would instead grab the last `testFx` release (currently `3.1.2`). Existing 3<sup>rd</sup>-party documentation might also be confusing to new users who find they can no longer access new versions with the old artifact name.

To remedy this, we could maintain two identical artifacts, `testfx` and `testFx`, which would allow us to keep both spellings working and up-to-date.

Is this possible? I'm not currently maintaining any Maven artifacts, so I'm not sure if there's an easy plugin to update two at the same time.

**Comment by hastebrot** [comment]
Hi John!

Unfortunately I have no access to the Maven group `org.loadui`. New releases will be uploaded to `org.testfx` and the artifacts are all lower case (e.g. `testfx-core:4.0.0-SNAPSHOT`). I also don't know about the implications on case-insensitive filesystems with both `testFx` and `testfx` artifacts.

**Comment by johnzeringue** [comment]
That sounds fine. I saw older stuff in the issue tracker hinting that things would move over to `org.testfx`, but I was thinking it might've been scraped.

Thanks!
