### ISSUE TITLE
Add method verifyThat(Predicate<R>), where R is the type of root node

### ISSUE THREAD

**Issue by TomasMikula** [TestFX/TestFX#186]
It would be nice to have a `verifyThat` method that tests some property of the root node. To do that, I propose to parameterize the `GuiTest` class by the type of the root node, and add a `verifyThat` method that tests the root node:

```java
class GuiTest<R extends Node> {
    protected abstract R getRootNode();

    public final void verifyThat(Predicate<R> test);
}

**Comment by hastebrot** [comment]
Hi! Good use case.

With the new API of TestFX 4.0-pre in `org.testfx.api` we could generalize this more and use fields of the test class. `stackPane` is the root `Node`. I also don't like to overfill `GuiTest` with too much responsibilities, but instead remove them (or allow the test developer to customize a base test class in whatever test framework he likes to use). The test class should hold references to the root `Node` and `FxAssert` (or `Assertions` in the example below) should be responsible for assertions. However your idea fits in the general implementation of `GuiTest` which contains a lot of convenience methods.

~~~java
public class StageRootTest {

    // FIXTURES.
    StackPane stackPane;
    Label label;

    // FIXTURE METHODS.
    @Before
    public void setupSpec() throws Exception {
        FxToolkit.registerPrimaryStage();
        FxToolkit.setupSceneRoot(() -> {
            label = new Label("foobar");
            stackPane = new StackPane(label);
            return stackPane;
        });
    }

    // FEATURE METHODS.
    @Test
    public void should_have_stage_root_with_label() {
        Assertions.verifyThat(stackPane, hasChild(label));
    }

    // HELPER METHODS.
    private Predicate<Parent> hasChild(Node node) {
        return (Parent parent) -> {
            return parent.getChildrenUnmodifiable().contains(node);
        };
    }

}
~~~

Also to note, that I implemented the helper method `hasChild()` in this example. There will be a more general, type-aware collection of `Matcher`s with #164. "General" means it will also support CSS queries, so we could use `stackPane`'s ID instead of the field `stackPane`. "Type-aware" means it will allow to expect certain class types and fail with a detailed description, if the types don't match.

**Comment by TomasMikula** [comment]
If I store a node as a field, such as `stackPane` in your example, and then in a test method manipulate that node, could it not interfere with the JavaFX application thread? For example

```java
@Test
public void test() {
    click(stackPane); // will be accessing stackPane on the JavaFX application thread
    doSomethingWith(stackPane); // accesses stackPane on the current thread
}
```

**Comment by hastebrot** [comment]
`click()` will wait for the JavaFX application thread to finish. `doSomethingWith()` will access the `Node` in the current thread. There is an issue (#143) that raised this problem. However there were no concrete problems with read-only accessing `Node` properties reported

**Comment by hastebrot** [comment]
Also [1] states:

>Node objects may be constructed and modified on any thread as long they are not yet attached to a Scene. An application must attach nodes to a Scene, and modify nodes that are already attached to a Scene, on the JavaFX Application Thread. 

[1] http://docs.oracle.com/javase/8/javafx/api/index.html?javafx/scene/Node.html

**Comment by hastebrot** [comment]
If this causes problem we'll need to modify integral classes like `NodeFinder` (that iterates over child `Node`s) or `PointLocator` (that accesses `layoutBound`s of `Node`s).

**Comment by TomasMikula** [comment]
OK, read-only access should cause no problems, if that access is properly synchronized with respect to JavaFX application thread access.

Is there a support for custom interactions that are not covered by the provided methods like `click()` and such? Basically just invoke something on the JavaFX application thread and wait for completion. So that I would not have to write

```java
@Test
public void test() {
    Platform.runLater(() -> interactWithMyNode(node));
    WaitForAsyncUtils.waitForFxEvents();
    verifyThat(...);
}
```

but only something like

```java
@Test
public void test() {
    interact(() -> interactWithMyNode(node));
    verifyThat(...);
}
```

**Comment by hastebrot** [comment]
There are `void setupFixture(Runnable)` and `T setupFixture(Callable<T>)` in `FxToolkit`, but it does not call `waitForFxEvents()` and also the method name indicates usage for setup and not interaction.

The (deprecated) `FXTestUtils` have a `invokeAndWait` that uses `WaitForAsyncUtils`. However you'll have to pass a parameter with a timeout to the method.

~~~java
public static void invokeAndWait(final Callable<?> task,
                                 int timeoutInSeconds) throws Exception {
    Future<?> future = WaitForAsyncUtils.asyncFx(task);
    WaitForAsyncUtils.waitFor(timeoutInSeconds, TimeUnit.SECONDS, future);
    WaitForAsyncUtils.waitForFxEvents();
}
~~~

Seems a good idea to add an `interact()` to `FxToolkit`.

**Comment by hastebrot** [comment]
As a sidenote: I like to let the test developer to fulfill most of his/her use cases with classes in `org.testfx.api` (and `org.testfx.matcher`). This is where the primary API resides. If there is need for customization, the other classes outside the primary API can be used and extended. The primary API contains some "anti-pattern" (i.e. static methods, god-classes and global context). It is designed with certain use-cases in mind and for convenience. The classes outside the primary API should be designed with for instance dependency injection in mind.

**Comment by hastebrot** [comment]
Also the primary API should be tested with acceptance and integration tests within `org.testfx.cases`. Those outside the primary API should be tested with unit-tests within the respective packages.

**Comment by TomasMikula** [comment]
What branch should I be looking at? I don't see any `org.testfx.api` package.

**Comment by hastebrot** [comment]
It is on `master`: https://github.com/TestFX/TestFX/tree/master/subprojects/testfx-core/src/main/java/org/testfx/api.

**Comment by hastebrot** [comment]
Also thinking about `interact()` I'm now not quite sure where it should go. `FxToolkit` should be generally responsible for setup and cleanup of fixtures, `FxRobot` for interaction with fixtures, and `FxAssert` (which is part of #164) for verification of the fixture's state.

**Comment by TomasMikula** [comment]
Ah, I was looking at 4.0-jdk8.

**Comment by hastebrot** [comment]
Sorry, I forgot to update these branches. 

My plan is, to get the PRs merged within the next two or three weeks, to finish a Gradle plugin for automatic creation of release notes and automatic releases by using Git tags, for continues deployment and start the beta phase with TestFX 4.0.0-beta.

**Comment by TomasMikula** [comment]
Nice, keep up the good work! ;)

**Comment by hastebrot** [comment]
Thanks.

**Comment by hastebrot** [comment]
`FxRobot#interact(Runnable)` and `FxRobot#interact(Callable<T>)` are now in `master`.

My PRs of December are merged. Automatic releases and decent javadocs are on their way. :smiley_cat:

**Comment by TomasMikula** [comment]
Nice!

**Comment by TomasMikula** [comment]
I guess `FxRobot#interact` didn't make it into 4.0.1-alpha?

**Comment by TomasMikula** [comment]
Oh, it's there. It is not a `static` method, I need to instantiate `FxRobot`.

**Comment by hastebrot** [comment]
#240 adds `FxRobot::interrupt()` which is a cousin to `FxRobot::interact()`. It is similar to the static method `WaitForAsyncUtils.waitForFxEvents()`, but has a shorter more memorizable method name.
