### ISSUE TITLE
Assertions.verifyThat(".table-view", TableViews.containsCell("123456")); throws NPE

### ISSUE THREAD

**Issue by purringpigeon** [TestFX/TestFX#187]
Hello,

When running a test - if a row contains a null value in one of the columns, the TableViews.containsCell will throw a NPE.

Null is a valid value for some data elements, therefore TestFX shouldn't throw a NPE, it should just consider the cell not equal.

**Comment by hastebrot** [comment]
Thanks a lot. Very good observation.

Changes are planned for TestFX 4.0 and tracked in #164.

**Comment by brcolow** [comment]
Should be fixed in TestFX 4.0 as noted above. Please let me know if this is still an issue. Thanks!
