### ISSUE TITLE
feat(Matcher): Reimplement `org.loadui.testfx.controls` in `org.testfx.matcher.{base, control}`.

### ISSUE THREAD

**Issue by hastebrot** [TestFX/TestFX#193]
- `org.loadui.testfx.controls.impl.EnabledMatcher`
  - [x] `Matcher<Object> enabled()`
  - [x] `Matcher<Object> disabled()`
- `org.loadui.testfx.controls.impl.VisibleNodesMatcher`
  - [x] `Matcher<Object> visible()`
- `org.loadui.testfx.controls.Commons`
  - [x] `Matcher<Object> hasText(String text)`
  - [x] `Matcher<Object> hasText(Matcher<String> matcher)`
  - [ ] `Node nodeLabeledBy(String labelQuery)`
  - [ ] <s>`Node nodeLabeledBy(Label label)`</s>
- `org.loadui.testfx.controls.TextInputControls`
  - [x] <s>`void clearTextIn(TextInputControl textInputControl)`</s>
  - [x] <s>`void clearTextIn(String textInputQuery)`</s>
- `org.loadui.testfx.controls.impl.ContainsNodesMatcher`
  - [x] `Matcher<String> contains(String domQuery)`
  - [x] `Matcher<String> contains(int numberOf, String domQuery)`
- `org.loadui.testfx.controls.impl.NodeExistsMatcher`
  - [x] `Matcher<String> exists()`
- `org.loadui.testfx.controls.ListViews`
  - [x] `int numberOfRowsIn(ListView<?> list)`
  - [x] `int numberOfRowsIn(String listQuery)`
  - [x] `Matcher<S> containsRow(Object rowValue)`
- `org.loadui.testfx.controls.TableViews`
  - [x] `int numberOfRowsIn(TableView<?> table)`
  - [x] `int numberOfRowsIn(String tableQuery)`
  - [x] `Matcher<S> containsCell(Object cellValue)`

**Comment by brcolow** [comment]
Are we still interested in implementing `Node nodeLabeledBy(String labelQuery)` or is this issue out-dated?

**Comment by brcolow** [comment]
Going to close this as the checklist is complete minus one item but we already have matchers that should cover it. Although honestly I don't understand the intent of `nodeLabeledBy` so it may be as-yet uncovered. We will fill in missing pieces of the API as the need arises (through people using TestFX and posting requests, and in our personal projects that use TestFX).
