### ISSUE TITLE
Headless mode still tries to access X11 display

### ISSUE THREAD

**Issue by RobzInadE** [TestFX/TestFX#208]
Hello, first time submitting an issue, bear with me.

I've tried to run my gui tests in headless mode to be able to use Jenkins CI in the future. The thing works beautifully locally on my Mac OS X Yosemite. 
Currently running with Oracle `JDK1.8.0_40` and `TestFX-core 4.0.1-alpha`
I run my tests with `mvn test -DargLine="-Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"`
And like I said, locally i see no GUI and tests passes. However, as soon as i try to run them on an actual headless machine (Jenkins CI with same JDK. Different OS: CentOS 6), i get this:

```
Failure in before hook:SettingsTabFeatureSteps.before()
Message: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:150)
	at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:291)
	at org.testfx.api.FxToolkit.setupApplication(FxToolkit.java:165)
	at com.memnon.printr.guitests.MyGuiTestHelper.initAndStart(MyGuiTestHelper.java:25)
```

Just asking if anyone else has noticed this?
Regards

**Comment by hastebrot** [comment]
Hi, thanks for the report!

AWT seems to cause the trouble:

~~~
java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
~~~

I'll try to reconfigure our continues integration (Travis CI) to run our tests headless in a second pass.

**Comment by hastebrot** [comment]
TODO:
- [ ] Upload [TestFX/Monocle](https://github.com/TestFX/Monocle) as `org.testfx:monocle:$version-$build` to jCenter (Bintray) and Maven Central (Sonatype).
- [ ] Add `./gradlew clean build -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw -Dprism.text=t2k -Dprism.verbose=true` to `.travis.yml`.

**Comment by hastebrot** [comment]
Working on this in #209.

**Comment by hastebrot** [comment]
The PR in #209 configures Travis to run our tests in headless mode without a framebuffer. Nearly all tests pass. Monocle seems to have problems to `Stage`s that are closed.

I couldn't reproduce the exception on the Travis Linux machine. I could try to debug this on my local Linux machine, but this needs to wait until next week. 

@RobzInadE In the meantine, could you try to run your tests with Maven and additionally use `-Djava.awt.headless=true`?

**Comment by RobzInadE** [comment]
@hastebrot Thanks for your quick investigation work! I really appreciate all this :+1: 
The `-Djava.awt.headless=true` flag doesn't seem to do anything special. I put it in my `-DargLine` parameter, but to no avail. 
My jenkins "goals" for the build now reads:
`test -Prun-gui-tests -DargLine="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"`

Running:
```
Started by user Robin
Building remotely on leeroy1 in workspace /var/jenkins/workspace/1-printr-build-and-test
[1-printr-build-and-test] $ /var/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.2.1/bin/mvn -f pom.xml -Dmaven.repo.local=/var/jenkins/workspace/1-printr-build-and-test/.repository test -Prun-gui-tests "-DargLine=-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"
[INFO] Scanning for projects...
...
```

results in the same exception as posted initially.

**Comment by hastebrot** [comment]
Hmm. And we can also assume that the command line arguments are passed to TestFX with `-DargLine` since you said that the tests pass locally and show no GUI. Otherwise this would have been a point to investigate.

**Comment by RobzInadE** [comment]
Stupid me! The `-Djava.awt.headless` works perfectly fine. It was a misconfiguration of mine!
My gui-tests are green and happy! :+1: 

Thanks!

**Comment by hastebrot** [comment]
That's very good. `-Djava.awt.headless` was more or less a wild guess by me. Nice, that it solves your problem. Thanks for confirming that it works.

**Comment by hastebrot** [comment]
BTW: I'll see if I can update the Monocle pre-builds for desktop systems to newer version of Java. I'm not sure at all if there were any changes to Monocle between Java 1.8.0_20 and 1.8.0_40. 

I'm also not sure how to name the versions for the pre-builds. Maybe `1.0.0+jdk.1.8.0_20` or `1.8.0_20-build.1` or something. The questions are
- whether we really need pre-builds of Monocle for different Java versions,
- how to increase the version number, if we need to make changes to the original Monocle code, and
- how to increase the version number, for Monocle in unreleased Java versions (like Java 1.8.0_60 or 1.9.0).

I think we can use `1.0.0` for the first released version of Monocle (i.e. the version in Java 1.8.0_20) and increase the minor version to `1.1.0` if changes were made to Monocle between Java versions. If we need to patch a certain Monocle version, we will update the patch version to for instance `1.0.1`.
