### ISSUE TITLE
Close request simulation doesn't work

### ISSUE THREAD

**Issue by longtimeago** [TestFX/TestFX#215]
I have following application:

``` java
public final class AppFX extends Application {
   @Override
   public void start(final Stage stage) {
      ...
    stage.setOnCloseRequest(
        new EventHandler<WindowEvent> {...}
    );
    stage.show()
   }
}
```

So, the hook is registered and it works when starting the app.
I'm trying to test that hook with TestFx:

``` java
public final class AppFXTest extends ApplicationTest {
    @Override
    public void start(final Stage stage) throws Exception {
        final AppFX app = new AppFX();
        app.start(stage);
    }

    @Test
    public void closesResources() throws Exception {
        this.closesResources();
        // this.push(KeyCode.ALT, KeyCode.F4).sleep(5000);
    }
}
```

I tried to start the test in debug but "close" hook is never called. Could someone give me a hint? It looks like an issue with TestFx.

Env

Java version: 1.8.0_40, vendor: Oracle Corporation OS name: "linux", version: "3.13.0-52-generic", arch: "amd64", family: "unix"

org.testfx.openjfx-monocle 1.8.0_20 org.testfx.testfx-core 4.0.1-alpha

**Comment by hastebrot** [comment]
Hi Paul!

Is the line with `this.push(...)` supposed to be called?

**Comment by longtimeago** [comment]
Hi, Benjamin
Actually, ```this.closesResources();``` do exactly the same as commented line.
I left that line commented just to note, that I also know (and tried) that approach :)

**Comment by hastebrot** [comment]
Seems you forgot to call `stage.show()` within `AppFX#start()` or `AppFXTest#start()`.

~~~java
import javafx.application.Application;
import javafx.scene.input.KeyCode;
import javafx.stage.Stage;

import org.junit.Test;
import org.testfx.framework.junit.ApplicationTest;

public final class AppFXTest extends ApplicationTest {
    @Override
    public void start(final Stage stage) throws Exception {
        final AppFX app = new AppFX();
        app.start(stage);
    }

    @Test
    public void should_close_stage_with_alt_f4() throws Exception {
        this.push(KeyCode.ALT, KeyCode.F4).sleep(5000);
    }

    public final class AppFX extends Application {
        @Override
        public void start(final Stage stage) {
            stage.setOnCloseRequest(windowEvent -> System.out.println(windowEvent));
            stage.show();
        }
    }
}
~~~

**Comment by hastebrot** [comment]
I'm also looking for a decent alternative for `Application` initialization. Something like `ApplicationTest.launch(AppFX.class)` would be nice.

**Comment by longtimeago** [comment]
@hastebrot ```stage.show()``` is actually there ... forgot to add it in the snippet

**Comment by hastebrot** [comment]
Hmm, the class I pasted actually prints out that the close request callback was called. I even didn't need to call `sleep()`.

Java 1.8.0_40, Windows 7.

**Comment by hastebrot** [comment]
Does this demo (needs to be under test sources) print the `WindowEvent` when you click on the button on the top?

~~~java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.input.KeyCode;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import org.testfx.api.FxRobot;

public class CloseStageDemo extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        Button pushKeysButton = new Button("push alt+f4");
        pushKeysButton.setOnAction(actionEvent -> {
            FxRobot robot = new FxRobot();
            robot.push(KeyCode.ALT, KeyCode.F4);
        });

        Button callCloseButton = new Button("call close()");
        callCloseButton.setOnAction(actionEvent -> {
            stage.close();
        });

        VBox sceneRoot = new VBox(pushKeysButton, callCloseButton);
        Scene scene = new Scene(sceneRoot, 200, 200);
        stage.setScene(scene);

        stage.setOnCloseRequest(windowEvent -> System.out.println(windowEvent));
        stage.show();
    }

}
~~~

**Comment by longtimeago** [comment]
@hastebrot Thank you for the test example! I'll check it tonight at home
For now, I can suggest the issue in java versions ... or something is wrong inside my ```AppFX```

**Comment by longtimeago** [comment]
@hastebrot your CloseStageDemo works for me ... it means that the issue is inside my app ... thank you! Will try to figure out the cause

**Comment by brcolow** [comment]
Closing due to time lapsed, please let me know if you still have a problem. Thanks!
