### ISSUE TITLE
Running tests via Maven + TeamCity: java.lang.IllegalArgumentException: WIDTH must be positive

### ISSUE THREAD

**Issue by brcolow** [TestFX/TestFX#224]
I am attempting to run some simple TestFX tests through maven and Teamcity. I am using the following JVM arguments:

`-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true`

Some other version infos:

````xml
    <dependency>
      <groupId>org.testfx</groupId>
      <artifactId>testfx-core</artifactId>
      <version>4.0.1-alpha</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testfx</groupId>
      <artifactId>testfx-junit</artifactId>
      <version>4.0.1-alpha</version>
      <scope>test</scope>
    </dependency>
````
`OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"`
`Apache Maven 3.2.3`
`Java version: 1.8.0_60-ea, vendor: Oracle Corporation`

Here is the full stack trace (notice none of it is actually *my* code, it's all internal JavaFX stuff) that happens for each test case:

````
java.lang.IllegalArgumentException: WIDTH must be positive
at com.sun.pisces.AbstractSurface.<init>(AbstractSurface.java:36)
at com.sun.pisces.JavaSurface.<init>(JavaSurface.java:37)
at com.sun.prism.sw.SWRTTexture.<init>(SWRTTexture.java:51)
at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:141)
at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:130)
at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
at java.lang.Thread.run(Thread.java:745)
````

I have tried adding `-Dprism.order=sw` but the I get the same result.

**Comment by hastebrot** [comment]
My wild guess is, that `NativeScreen` of Monocle uses its `width` member field and `com.sun.pisces.AbstractSurface` uses this information. If so, we might change the `width` to a positive value.

https://github.com/TestFX/Monocle/blob/0ab3986f4c/src/main/java/com/sun/glass/ui/monocle/headless/HeadlessScreen.java#L48

**Comment by brcolow** [comment]
Okay - let me know if you need anything on my end. Thanks very much.

**Comment by hastebrot** [comment]
>some simple TestFX tests

So, the exception can be reproduced with a test that shows an empty JavaFX `Stage`?

**Comment by brcolow** [comment]
Doing some testing to find the simplest possible test that will recreate the issue - will update this when I find it.

**Comment by brcolow** [comment]
I have created a reproducible test case for you. It involves a custom control - which is an AutoCompleteComboBox. It is quite simple indeed. You create one by passing in a list of values from which potential auto complete candidate matches are selected. Two modes are available, starts-with and contains (each being pretty self explanatory). The code is based largely on a [StackOverflow post](http://stackoverflow.com/questions/19924852/autocomplete-combobox-in-javafx). 

Here is the control and the corresponding test:

https://gist.github.com/brcolow/e0eea9abac0abc1a5005

**Comment by hastebrot** [comment]
Thanks for the good work. I'll try this out.

**Comment by brcolow** [comment]
Curious if you have been able to reproduce.

**Comment by hastebrot** [comment]
The TeamCity server lets us choose between running the service under the system account or a user account. I'll test, if this makes a difference.

**Comment by brcolow** [comment]
I was able to make some progress on this issue (after we talked)...I was able to get all but one test to pass. The stacktrace of the error for this one test is here:

https://gist.github.com/brcolow/5e4bc89b936d80b590ae

The testcase that is failing is:
````java
    @Test
    public void testAutoCompleteStartsWithMode()
    {
        // given
        autoCompleteComboBox.setAutoCompleteMode(AutoCompleteComboBox.AutoCompleteMode.STARTS_WITH);
        assertThat(autoCompleteComboBox.getAutoCompleteMode()).isEqualTo(AutoCompleteComboBox.AutoCompleteMode.STARTS_WITH);

        press(KeyCode.A);
        release(KeyCode.A);

        assertThat(autoCompleteComboBox.getComboBox().getItems()).containsExactly("Açaí", "Apple", "Apricot", "Avocado",
                "Ackee");

        press(KeyCode.P);
        release(KeyCode.P);

        assertThat(autoCompleteComboBox.getComboBox().getItems()).containsExactly("Apple", "Apricot");

        press(KeyCode.P);
        release(KeyCode.P);

        assertThat(autoCompleteComboBox.getComboBox().getItems()).containsExactly("Apple");
    }
````

**Comment by hastebrot** [comment]
Even better it has something to do with Monocle and `Window#close`.

~~~
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at com.sun.glass.ui.monocle.MonocleWindowManager.repaintAll(MonocleWindowManager.java:163)
    at com.sun.glass.ui.monocle.MonocleWindow.notifyDestroy(MonocleWindow.java:427)
    at com.sun.glass.ui.monocle.MonocleWindowManager.closeWindow(MonocleWindowManager.java:106)
    at com.sun.glass.ui.monocle.MonocleWindow._close(MonocleWindow.java:178)
    at com.sun.glass.ui.Window.close(Window.java:323)
~~~

**Comment by brcolow** [comment]
Indeed..I will post an issue on the JavaFX mailing list =). Thanks again.

**Comment by hastebrot** [comment]
Please note that you use Monocle for 8u20 for a newer JavaFX version. This might cause the issue.

I looked through my mails and found out that `-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k` are the preferred JVM args. We need `-Dprism.order=sw` to support screenshots in headless mode. And `-Dprism.text=t2k` to workaround an exception. I'll see if I can find the exact exception.

**Comment by hastebrot** [comment]
The tests `AutoCompleteComboBoxTest` now pass completely and then (in another test run) fail completely with TeamCity. It seems that this is a timing issue.

**Comment by hastebrot** [comment]
`-Dprism.text=t2k`: This was a workaround for a core dump caused by a problem related to font smoothing. https://bugs.openjdk.java.net/browse/JDK-8087581

I guess this is not related to this issue.

**Comment by brcolow** [comment]
It appears I am getting an intermittent failure on one of my tests. If it is a timing issue, how does one fix it? Thread.sleep() ?
