### ISSUE TITLE
Can't get  org.testfx.framework.junit.ApplicationTest from library

### ISSUE THREAD

**Issue by octaviospain** [TestFX/TestFX#225]
I'm starting to uso TestFX and I added the dependencies from maven, and I can see them added to my project:
![captura de pantalla 2015-06-11 a las 13 21 41](https://cloud.githubusercontent.com/assets/2102234/8105830/dfc5d3bc-103c-11e5-836d-125dd531343e.png)

but I can't get the org.testfx library in order to extends from ApplicationTest.
I've reviewed the maven settings severa times but I can't fix it.

I have this dependencies and repositories in my pom.xml file:

`<dependencies>`
   ` <dependency>`
      `<groupId>junit</groupId>`
      `<artifactId>junit</artifactId>`
      `<version>4.12</version>`
      `<scope>test</scope>`
    `</dependency>`
    `<dependency>`
      `<groupId>org.testfx</groupId>`
      `<artifactId>testfx-core</artifactId>`
      `<version>4.0.0-SNAPSHOT</version>`
      `<scope>test</scope>`
    `</dependency>`
  `</dependencies>`
  `<repositories>`
    `<repository>`
      `<snapshots>`
        `<enabled>false</enabled>`
      `</snapshots>`
      `<id>maven-central-repo</id>`
      `<url>http://repo1.maven.org/maven2</url>`
    `</repository>`
    `<repository>`
      `<snapshots>`
        `<enabled>true</enabled>`
      `</snapshots>`
      `<id>sonatype-snapshots-repo</id>`
      `<url>https://oss.sonatype.org/content/repositories/snapshots</url>`
    `</repository>`
    `<repository>`
      `<snapshots>`
        `<enabled>false</enabled>`
      `</snapshots>`
      `<id>central</id>`
      `<name>Central Repository</name>`
      `<url>https://repo.maven.apache.org/maven2</url>`
    `</repository>`
  `</repositories>`

Thanks in advance

**Comment by hastebrot** [comment]
hi!

you can find a list of artifacts at https://search.maven.org/#search%7Cga%7C1%7Corg.testfx

you need testfx-junit for applicationtest. it is available from,mavencentral.

(sorry for brevity, I'm on mobile)

**Comment by octaviospain** [comment]
Thank you for your brevity!
