### ISSUE TITLE
Test scrollbar of a TextArea control

### ISSUE THREAD

**Issue by gelineusa** [TestFX/TestFX#230]
Hi,

I am a newbie to TestFX. I tried to write a test to test the scrollbar of a TextArea control (when wrapText is set) but I could not find the information anywhere. Is this possible in testFX? Has anyone done this before? 

Any tips/information would be appreciated.

Thanks,

**Comment by hastebrot** [comment]
Hey,

I've never done this before. It is possible to do this programmatically (i.e. directly on the `ScrollPane`) described at [1]. Another approach is to use `drag()` and `dropTo()` on the `ScrollPane`, but I have no concrete code example for this, yet.

[1] http://stackoverflow.com/questions/15840513/javafx-scrollpane-programmatically-moving-the-viewport-centering-content

**Comment by gelineusa** [comment]
Thanks for the reply. I also found that ScrollBar has a function isVisible() that can tell if the feature is working.
