### ISSUE TITLE
DesktopPane from README example not found

### ISSUE THREAD

**Issue by sgramsch** [TestFX/TestFX#241]
Hi,
just wanted to run the example from the readme. Unfortunately the imports are not declared, and I did not find DesktopPane that is used by the test.
Is that example still valid?
Thanks,
Stefan

**Comment by hastebrot** [comment]
Hi Stefan,

the example `DesktopPaneTest` is still valid. Unfortunately there is no `DesktopPane` and it is rather complicated to implement it, I mean for a simple first example. Another issue is, that some people think the example simulates user action on the OS's desktop (Windows, KDE, Gnome, ...).

What I like about the `DesktopPaneTest` is, that it showcases mouse click simulation with `clickOn()` and `rightClickOn()`, keyboard interaction with `write()` and `push()`, drag and drop interactions with `drag()` and `dropTo()` and usage of `Node` queries via CSS identifier, CSS class and text label. Pretty much to most basic parts of TestFX.

Would be really great, if we find another example, that covers a similiar amount of use-cases, but is easier to implement and less confusing.

**Comment by sgramsch** [comment]
Thanks for the clarification, Benjamin.
