### ISSUE TITLE
Windows 10 scaling issue

### ISSUE THREAD

**Issue by Daedelus1982** [TestFX/TestFX#245]
First of all, TestFX is a great, very useful tool but seems to struggle with Windows 10 scaling. If I ask TestFX to click on a button on my hi-res screen of 2736x1824 with a scaling of 200%, it seems to click on the button at the 100% scale so it misses the button by quite a long way. If I change my scaling to 100% and restart the computer the same tests work fine.

So it seems when looking up a button it grabs the coordinates of the button at the wrong scale.

By the way, I am using JDK 8u71 and testFX 4.0.1-alpha. Is there a simple argument I can apply to work around this?

**Comment by Daedelus1982** [comment]
I have developed a workaround for this issue, if you add something like this: -DSCALE=200 (assuming your screen is scaled to 200%) to the command line then you can grab this argument in your code with something like this 

```java
String SCALE = System.getProperty("SCALE");
SCALEDPERCENT = SCALE != null ? Double.parseDouble(SCALE) : 100;
```

Now we can use this value to multiply our click points. Here are two of the methods are used for this task:

```java
    public static Point2D getScaledClickPointForNode(Node unscaledNode, double scaledPercent)
    {
        double scaledValue = scaledPercent / 100;
        Point2D topLeftPoint = unscaledNode.localToScreen(0, 0);
        Point2D scaledPos = getScaledPoint(topLeftPoint, scaledPercent);
        Rectangle scaledNode = new Rectangle(scaledPos.getX(), scaledPos.getY(),
                unscaledNode.getBoundsInLocal().getWidth() * scaledValue,
                unscaledNode.getBoundsInLocal().getHeight() * scaledValue);

        return new Point2D(scaledNode.getX() + scaledNode.getWidth() / 2, scaledNode.getY() + scaledNode.getHeight() / 2);
    }

    public static Point2D getScaledPoint(Point2D unscaledPoint, double scaledPercent)
    {
        double scaledValue = scaledPercent / 100;
        return new Point2D(unscaledPoint.getX() * scaledValue, unscaledPoint.getY() * scaledValue);
    }
```

For unscaled screens I do not need to add the argument to the command line so everything works without changes for those guys. 

It is not an ideal solution but it works for now.

**Comment by hastebrot** [comment]
There is a `Screen::getRenderScale()` which returns `1.0` for normal displays and `2.0` for retina displays. We could use this, to automatically recognize scaled displays and change the bounds query for nodes.

**Comment by DaTeL237** [comment]
I'm running into the same issue, here's a reproduction in a single file. Test passes on 100% scale but fails on others (I tested with 150%)

see also: https://github.com/TestFX/TestFX/issues/226

```
import javafx.application.Application;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import org.junit.Test;
import org.testfx.framework.junit.ApplicationTest;

import static org.testfx.api.FxAssert.verifyThat;

public class MenuBarTest extends ApplicationTest {
    SimpleApp app;

    @Override
    public void start(Stage stage) {
        app = new SimpleApp();
        app.start(stage);
    }

    @Test
    public void startNewFile() {
        clickOn("File");
        clickOn("New");

        verifyThat((Node) null, (node) -> app.itemClicked);
    }


    public class SimpleApp extends Application {

        public boolean itemClicked = false;

        @Override
        public void start(Stage primaryStage) {
            // Build a menu with: File > New
            MenuItem newFileItem = new MenuItem("New");
            newFileItem.setOnAction(event -> itemClicked = true);
            Menu fileMenu = new Menu("File", null, newFileItem);
            MenuBar menuBar = new MenuBar(fileMenu);

            // Start a scene with the menu bar inside it
            VBox vbox = new VBox(menuBar);
            Scene scene = new Scene(vbox, 600, 400);
            primaryStage.setScene(scene);
            primaryStage.show();
        }
    }
}
```

**Comment by nickavv** [comment]
It sounds like you have a reasonable solution, could you possibly prioritize this? 4k monitors are only getting more prevalent and writing tests that pass locally is basically impossible at this time.

**Comment by Aidamina** [comment]
I had the same issue in my project, and i found a satisfactory workaround by replacing the BoundsLocator in the initialisation of my test:

    robotContext().setBoundsLocator(new BoundsLocatorImpl(){
        @Override
        public Bounds boundsOnScreenFor(Node node) {
            Bounds bounds = super.boundsOnScreenFor(node);
            return ScaledBounds.wrap(bounds);
        }
    });
    robotContext().setPointLocator(new PointLocatorImpl(robotContext().getBoundsLocator()));

You will also need the ScaledBounds class:

    import javafx.geometry.BoundingBox;
    import javafx.geometry.Bounds;
    import javafx.stage.Screen;
    
    import java.awt.*;
    
    public class ScaledBounds extends BoundingBox {
    
        private static final double scale;
        static {
            scale = Toolkit.getDefaultToolkit().getScreenSize().getWidth() / Screen.getPrimary().getBounds().getWidth();
        }
    
        public static ScaledBounds wrap(Bounds bounds){
            return new ScaledBounds(bounds);
        }
        private ScaledBounds(Bounds wrapped){
            super(
                    wrapped.getMinX() * scale,
                    wrapped.getMinY() * scale,
                    wrapped.getMinZ() * scale,
                    wrapped.getWidth() * scale,
                    wrapped.getHeight() * scale,
                    wrapped.getDepth());
        }
    }

**Comment by brcolow** [comment]
Thanks for posting the workaround. Would you be willing to open a PR that fixes this issue?

**Comment by nickavv** [comment]
The workaround lets my tests pass when run through Eclipse, however because `Toolkit.getDefaultToolkit()` returns `HeadlessToolkit` when run in headless mode, the `getScreenSize()` call throws a `HeadlessException` when run in a headless environment.

Since tests typically need to run in a headless environment to be compatible with, say, a continuous integration build, this isn't a perfect workaround. I'm currently trying a few other things and will report back if I have any success.

**Comment by Aidamina** [comment]
@nickavv 
In headless mode there is no screen, so you should prevent an exception by doing an assume in your test to check for headless mode. Its working as intended as far as I can see.

I too use jenkins for our CI. And I have no problems running ui tests with this workaround using de jenkins Xvfb plugin.

**Comment by Aidamina** [comment]
@brcolow 
If I have some time in the next few weeks I'll put together a PR that fixes this. Feel free to bug me if you haven't heard anything in a few weeks.

**Comment by parszab** [comment]
I can confirm this on Linux with `-Dglass.gtk.uiScale=2.0` or after running: 

`gsettings set org.gnome.desktop.interface scaling-factor '2'`

**Comment by brcolow** [comment]
Ping @Aidamina - still interested in that PR? 😄
