### ISSUE TITLE
Platform.exit()

### ISSUE THREAD

**Issue by anton-johansson** [TestFX/TestFX#247]
When I use ```Platform.exit()``` at points where I want to force a direct exit of the application, my unit tests with TestFX seem to hang. I'm guessing they're not shutting down properly.

Is it a bad idea using ```Platform.exit()```, or can this be fixed within TestFX somehow?

**Comment by hastebrot** [comment]
>Is it a bad idea using Platform.exit()

Yes it is. It will shut the JavaFX Application Thread down. Any new request to the thread, e.g. using `Platform.runLater()` will cause the application to hang.

This also caused me some headaches searching for a bug when all `Stage`s were closed. If they were all closed, JavaFX will automatically call `Platform.exit()`. I fixed that in [1].

>can this be fixed within TestFX somehow

There is no workaround I know.

[1] https://github.com/TestFX/TestFX/blob/35c48e8513/subprojects/testfx-core/src/main/java/org/testfx/api/FxToolkit.java#L266-L268

**Comment by anton-johansson** [comment]
That explains a lot, thanks! I guess I'll try to avoid using ```Platform.exit()```.

I have a scenario where I never actually show a stage. And it seems to me that doing ```stage.close()``` on this stage won't cause the application to close properly. Here is one example where I used ```Platform.exit()```. I'll see if I can find a better workaround for that.

**Comment by aminabs** [comment]
Just call platform.setImplicitExit(false) to avoid your application being implicitly closed after all the stages are gone.
