### ISSUE TITLE
JUnit Rules: StageRule and ApplicationRule

### ISSUE THREAD

**Issue by hastebrot** [TestFX/TestFX#253]
``` java
public interface TestFixture {
    void before() throws Exception;
    void after() throws Exception;
}

public interface ApplicationFixture {
    void init() throws Exception;
    void start(Stage primaryStage) throws Exception;
    void stop() throws Exception;
}
```

---

JUnit and Hamcrest (which offer `org.junit.Test`, `org.junit.Assert` and `org.hamcrest.CoreMatchers`) are well-known in the Java ecosystem. JUnit 4.11 is used in more than 10,000 and Hamcrest 1.3 in more than 1,000 artifacts on Maven Central.

JUnit 4.9 (released on August 22, 2011) added `TestRule` which can be annotated with `@ClassRule`, or `@Rule`

**Comment by brcolow** [comment]
I think this was implemented already with the testfx-junit subproject. Thus, closing.
