### ISSUE TITLE
TestFX Chat

### ISSUE THREAD

**Issue by brcolow** [TestFX/TestFX#260]
@hastebrot would you be open to creating an official chatroom for TestFX? We could go the traditional IRC route or one of the newer alternatives such as gitter.im. My primary interest in a such a room would be to make it easier to discuss short-term, long-term goals of TestFX, foster contributions, help new people, etc.

If we decide IRC, we could add a note to the README.md. If we decide gitter.im, we could add a badge to the README.

**Comment by hastebrot** [comment]
That's a great idea. I've created a Gitter repository channel (https://gitter.im/TestFX/TestFX). Will add a Gitter badge to the `README.md` later. I'm regulary on Freenode/IRC, but am not connected to the server permanently.

**Comment by hastebrot** [comment]
TestFX also has a Kanban-like board at Waffle.io (https://waffle.io/TestFX/TestFX). But I'm not sure if it is useful.
