### ISSUE TITLE
Failing test in org.loadui.testfx.TextInputControlsTest

### ISSUE THREAD

**Issue by Ortner** [TestFX/TestFX#276]
## Issue

The following tests are failing:

```
org.loadui.testfx.TextInputControlsTest > shouldClearText FAILED
    java.lang.AssertionError at TextInputControlsTest.java:47
        Caused by: java.lang.AssertionError at TextInputControlsTest.java:47
```

As they do not fail on the Build-Server or are skipped (at least I couldn't find anything in the protocols). I assume the issue depends on my specific platform:
- Operating system: Apple OSX ElCapitan (10.11.4)
- Java: Oracle JDK8 (build 1.8.0_91-b14)
## Behaviour of test

``` Java
    @Test
    public void shouldClearText() {
        clickOn(TEXT_FIELD).write("Some text");
        verifyThat(TEXT_FIELD, hasText("Some text"));

        push(TAB); // To change focus from the TextField.

        clearTextIn(TEXT_FIELD);
        verifyThat(TEXT_FIELD, hasText(""));
    }
```

The text is correctly typed and verified in the first two lines. Within the rest of the test the last character is removed. And the test fails at the last verify.
## Analysis

The method clearTextIn() in in TextInputControls uses the following code to clear the TextField:

``` Java
fx.push(CONTROL, A).push(BACK_SPACE);
```

The keyboard shortcut to select all text on a Mac is 'command+A' actually.
## Proposed Solution

Either implement a platform specific behaviour or use the platform independent solution provided by `public static void clearTextIn(TextInputControl textInputControl)`

**Comment by JordanMartinez** [comment]
@Ortner I've just started using TestFX, so I'm not familiar with its inner workings. However, shouldn't the system dependent `fx.push(CONTROL, A)` be the system independent `fx.push(SHORTCUT, A)`?

Is there some code code in the inner workings that screws this up or something?

**Comment by Ortner** [comment]
@JordanMartinez I actually didn't new about the shortcut keycode. But as there is no need in using input events to clear the TextField, in my opinion the method used in #277 is the better solution.

Do you see any reason for using KeyEvents?

**Comment by JordanMartinez** [comment]
> Do you see any reason for using KeyEvents?

To some extent, yes and no. 
Yes: because it would realistically simulate what would occur if one interacted with the `TextInputControl`. 
No: because what's the point of spending unneeded time in event handlers since we already know that it will only delete the text?

The 'yes' reason would be better than the 'no' in terms of principle, but the 'no' better than the 'yes' in terms of test speed & performance
