### ISSUE TITLE
KeyCode.SHORTCUT does not convert into System-dependent shortcut KeyCode

### ISSUE THREAD

**Issue by JordanMartinez** [TestFX/TestFX#290]
By principle, `ApplicationTest#press(SHORTCUT)` should run a `Node`'s `CONTROL` handler for Windows/Linux and the `COMMAND` for Mac

**Comment by damithc** [comment]
We are waiting for a fix for this as well.

**Comment by JordanMartinez** [comment]
Does anyone know why there hasn't been any commit activity in the past month and a half? (Last commit was on May 9 and #285 looks like it should have been merged but surprisingly hasn't yet....)

**Comment by hastebrot** [comment]
@JordanMartinez I was very busy. Will look into the PRs when I find time.

**Comment by JordanMartinez** [comment]
@hastebrot thanks for the quick response. I'm grateful for all the time you and the others have put into this project.

**Comment by damithc** [comment]
I second @JordanMartinez 
The world needs TestFx. Hope @hastebrot et al will continue to develop this very useful tool. :-)

**Comment by DmitriBoulanger** [comment]
i am waiting for the TestFX 4 release ... Could you please say a bit what are your plans?

**Comment by hastebrot** [comment]
I try to outline a bit of the future plans for the release in #292.

**Comment by brcolow** [comment]
PR welcome!

**Comment by brcolow** [comment]
Fixed by #320 - thanks to JordanMartinez
