### ISSUE TITLE
Infinite KeyPressed event loop

### ISSUE THREAD

**Issue by flef** [TestFX/TestFX#295]
Hi,

I'm launching a Test with JUnit on a Linux Debian machine inside a Eclipse Mars IDE.

``` Java
@Test
public void writeInTextFieldAndPressEnter()
{
    clickOn("#myNode").write("something").press(KeyCode.Enter);
}
```

The test run successfully but when it stops, the Enter Key continue to raise KeyPressed Event. That's to say, if I open a new window like Gedit, a lot of new line characters are inserted inside it.

When I finally stop the Eclipse IDE, the KeyPressed Event stops being raised.

Do you have any clue of what happen ?

**Comment by flef** [comment]
Ok, It was not clear for me that we have to call release function after the press one to perform a single keyPressed event.

```java
@Test
public void writeInTextFieldAndPressEnter()
{
    clickOn("#myNode").write("something").press(KeyCode.Enter).release(KeyCode.Enter);
}
```

By the way, the described behavior is not suitable. All pressed keys should be release by the ApplicationTestClass by the end of the tests.

**Comment by JordanMartinez** [comment]
Use “press()” instead

**Comment by JordanMartinez** [comment]
Sorry, I meant “push()”

**Comment by flef** [comment]
Thanks, I'll try it.

Anyway, we should release all the pressed keys by the end of the test.
Maybe we can add a @After methode which dors that.

**Comment by JordanMartinez** [comment]
I agree with that. Otherwise, it can screw with your computer, especially if you pressed but did not release the CTRL key (or SHIFT or ALT for that matter). I made that mistake and had to log out and log in multiple times until figure out the cause.

**Comment by brcolow** [comment]
Any suggestions for such an `@After` method? That is, what would be the best way to release all the keys after a test?

**Comment by JordanMartinez** [comment]
@brcolow I'm pretty sure it is. Alos, `KeyboardRobotImpl#releasePressedKeys` is the method that would need to be called, which is currently private.
