### ISSUE TITLE
Wait for page to show up before running tests

### ISSUE THREAD

**Issue by Freemanhack** [TestFX/TestFX#296]
Example: 
we have 1 window to get list of pdf from search engine.
another one is Download progress window.
and last page for view if pdf completed download.

How its work:
start by select 1 pdf in list to download then
download progress window download show up and wait for complete download 
Test case will be start here at pdf viewer window

Thanks in advanced for your help
sorry for bad English

**Comment by hastebrot** [comment]
You can use `WaitForAsyncUtils.waitFor(timeout, timeUnit, condition)` to wait for the progress bar in the progress window to complete. In the `condition` you `lookup()` the progress bar control and check if the progress value is `1.0`, i.e. finished.

**Comment by Freemanhack** [comment]
Thank you very much for your answer.
