### ISSUE TITLE
How to test Alert Dialoges?

### ISSUE THREAD

**Issue by ThomasDaheim** [TestFX/TestFX#299]
I have managed to test most of my application using TestFX (3.1.0). But one thing I haven't managed so far:

At various places the code raises Alert Dialoges. I can trigger them but I haven't found a way to test them afterwards. I tried something like:

In my application:
```
// add info to alert for later lookup
alert.getDialogPane().getStyleClass().add(".alertDialog");
alert.initOwner(borderPane.getScene().getWindow());
```

In my test class:
```
final DialogPane alertDialog = (DialogPane) find(".alertDialog");
assertNotNull(alertDialog);
```

But the assert fails. How can I get a hold on the alert dialog in my test class?

**Comment by levinnd** [comment]
Assuming that's a javafx.scene.control.Alert, the header text and the content text are both stored in labels inside the alert's dialog pane. So you can do:

`Label label = find("This is my header text in my alert");
DialogPane pane = (DialogPane) (((GridPane)label.getParent()).getParent());`

And that should give you the dialogPane for the alert.

**Comment by ThomasDaheim** [comment]
Seems to work! Thanks a lot. Not sure why it doesn't work with looking up css but thats good enough for me :-)

**Comment by schubkatze** [comment]
When adding a css id or css styleclass in Java Code you normally don't write '.' or '#' bevor the actual id/styleclass. Maybe that's the problem here.

**Comment by schubkatze** [comment]
When adding a css id or styleclass in Java Code you normally don't write '#' or '.' bevor the actual id/styleclass. Maybe that's the problem here.

**Comment by ThomasDaheim** [comment]
Yep, thats what I figured out shortly after posting as well :-)
