### ISSUE TITLE
testfx cann't get dynamic info?

### ISSUE THREAD

**Issue by Rhain** [TestFX/TestFX#300]
I had a label with text "" at begining, then I set the label with a text "aaa".
Then, I test the label with testfx : `FxAssert.verifyThat("#label", NodeMatchers.hasText("aaa"));`
but the test failed,because testfx get the test of the label is "".

Is testfx cann't get the text after the label changed?

The same problem appeared on javafx node's visible or disable properteries.Once I init a node with visible or disable, after I changed the node's visible or disable property ,testfx cann't get the visible or disable property correctly!

How can I fix the problem? 

Thanks!

**Comment by RobzInadE** [comment]
I have no problems doing this.
Make sure you're modifying the label on the main javafx thread. Otherwise the changes may not propegate properly. If you're outside the javafx thread, use `Platform.runLater`

**Comment by brcolow** [comment]
Can you produce a failing unit test illustrating the problem?

**Comment by JordanMartinez** [comment]
@brcolow Since there's been no response for a year, can this be closed as an unconfirmed problem?
