### ISSUE TITLE
Screenshot feature removed in 4.0.4

### ISSUE THREAD

**Issue by adamish** [TestFX/TestFX#306]
The screenshot on failure functionality in 3.x appears to have been removed in 4.0.4.

Could this be restored?

**Comment by hastebrot** [comment]
This is planned for the next release.

**Comment by brcolow** [comment]
I am not sure but I think that to implement this feature for the junit5 provider we will need https://github.com/junit-team/junit5/issues/618 to be resolved. I will work on adding this functionality to the junit4 provider either in https://github.com/TestFX/TestFX/pull/355 where the capture functionality was added or I will extract out the capture functionality from 355.

**Comment by brcolow** [comment]
I think that screenshot capture should be moved out of `testfx-core` and into the junit sub-projects. This way we can get better naming for the saved images and even report the failures with their respective screenshots by utilizing reporter functionality. As I stated I believe `junit5` is not quite yet ready to support this (however I could be wrong about that and if so, yay) but `junit4` can certainly support this with its' `TestWatcher` interface. I will work on this and open a PR very soon.

**Comment by hastebrot** [comment]
>screenshot capture should be moved out of testfx-core and into the junit sub-projects

Sounds good to me. :smiley:

**Comment by raniejade** [comment]
Is there a plan to re-enable this?

```java
private static <T> void verifyThatImpl(String reason,
                                           T value,
                                           Matcher<? super T> matcher) {
        try {
            MatcherAssert.assertThat(reason, value, matcher);
        }
        catch (AssertionError error) {
            // TODO: make error capture and assertion throw more reliable.
            // captureErrorScreenshot();
            throw new AssertionError(error.getMessage());
        }
    }
```

**Comment by JordanMartinez** [comment]
@brcolow Should this feature be re-added to `DebugUtils`? One could execute the `captureErrorScreenshot()` using `DebugUtils#runCode`, correct?

**Comment by brcolow** [comment]
Can we add the auto-capture behavior to `informedErrorHandler()`? It could print out the location of the screenshot (not super useful for CI without further infrastructure in place such as uploading failure screenshots to some s3 bucket or something) but definitely useful when running the our test suite (or developers using TestFX to run their tests locally) locally.

**Comment by adamish** [comment]
I ended writing a simple JUnit @Rule that catches any exception and takes screenshot. I found this more useful as my tests involve fx matchers, various junit/hamcrest asserts and mockito. This approach works in all cases...

**Comment by brcolow** [comment]
@adamish IMO it makes sense for TestFX `verifyThat` calls to take and save a screenshot as TestFX is for testing GUI behavior. In many cases exceptions could be thrown from non-UI related infrastructure in a UI test (and could fail a junit/hamcrest assertion) and taking a screenshot in this case would provide no useful information. We should make the screenshot feature of `verifyThat` as easy as possible to toggle (should it default to off?) on or off, but I think it has a very logical place as part of the TestFX library functionality.

**Comment by JordanMartinez** [comment]
I agree with @brcolow. Although one could use a Rule to accomplish this, the code I've written in #422 also allows a developer to take a screenshot of the test even when it doesn't fail without needing to get deep into TestFX's still undocumented API. I'm not sure why one would want to do that, but you never know.

**Comment by JordanMartinez** [comment]
@brcolow Do you close issues immediately after they've been fixed/resolved (like this one) or only after there is a new release with the fix?

**Comment by brcolow** [comment]
I haven't really came up with a policy TBH. I think closing as soon as they are fixed/resolved makes sense - most of the time I just forget.

**Comment by JordanMartinez** [comment]
Thanks for the clarification. Yeah... the admin work behind open source projects can be a pain...
