### ISSUE TITLE
onClick clicks wrong menu item

### ISSUE THREAD

**Issue by jibbe** [TestFX/TestFX#309]
I'm using 4.0.4-alpha.

I have two menus: File | Edit
Under File there is an item, "New File"
When I issue a call:
clickOn("#fileMenu").clickOn("#newMenuItem");
It clicks on the first item in the Edit menu. I can see the Edit menu get lit up when the test is running and I've confirmed it goes into the incorrect onAction handler..

Is this the correct way to trigger a menu item selection? Is this a bug? Any work around?

**Comment by jibbe** [comment]
I have a simple work-around:
clickOn("#fileMenu").moveBy(1, 1).clickOn("#saveMenuItem");

This causes the fileMenu to stay open, which allows the second clickOn call to succeed.

I couldn't find any test cases in the source.

**Comment by brcolow** [comment]
Would you have time to create a unit test that demonstrates the failure? Then I will investigate the best way to solve this issue.

**Comment by jibbe** [comment]
Sorry for the delay. Here is a simple (crude) test case.

package org.testfx.cases.issue;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyCodeCombination;
import javafx.scene.input.KeyCombination;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import org.junit.Test;
import org.testfx.api.FxToolkit;
import org.testfx.cases.TestCaseBase;

import org.junit.Before;
import org.junit.BeforeClass;
import org.testfx.api.FxRobot;

public class MenuBarClickTest extends TestCaseBase {

    public FxRobot fx = new FxRobot();

    CompletableFuture future = new CompletableFuture();

    @BeforeClass
    public static void setupSpec() throws Exception {
        FxToolkit.registerPrimaryStage();
    }

    @Before
    public void setup() throws Exception {
        FxToolkit.setupStage(stage -> {
            MenuBar menuBar = new MenuBar();
            
            Menu fileMenu = new Menu("File");
            fileMenu.setId("fileMenu");

            MenuItem newItem = new MenuItem("New");
            newItem.setId("newItem");
            newItem.setOnAction((actionEvent) -> {
               future.complete(true);
            });
            fileMenu.getItems().add(newItem);

            MenuItem saveAsItem = new MenuItem("Save As....");
            saveAsItem.setId("saveAsItem");
            saveAsItem.setAccelerator(new KeyCodeCombination(KeyCode.S, KeyCombination.SHIFT_DOWN, KeyCombination.CONTROL_DOWN));
            fileMenu.getItems().add(saveAsItem);
            
            menuBar.getMenus().add(fileMenu);
            
            Menu editMenu = new Menu("Edit");
            editMenu.setId("editMenu");
            
            MenuItem cutItem = new MenuItem("cut");
            cutItem.setId("cutItem");
            editMenu.getItems().add(cutItem);
            
            menuBar.getMenus().add(editMenu);
         
            StackPane pane = new StackPane(new VBox(menuBar));
            pane.setAlignment(Pos.CENTER);
            Scene scene = new Scene(pane, 300, 400);
            stage.setScene(scene);
            stage.show();
        });
    }
    
    @Test
    public void node_queryFirst_returns_node() throws Exception {
        
        fx.clickOn("#fileMenu").clickOn("#newItem");
        
        //work around
        //fx.clickOn("#fileMenu").moveTo(10,10).clickOn("#newItem");

        future.get(3, TimeUnit.SECONDS);
        
    }
}

**Comment by brcolow** [comment]
Thanks a lot, please give me a little bit to investigate.

**Comment by jibbe** [comment]
Interesting. That explains why the work around worked!!

Would it be possible (and make sense) in the onClick to determine the type of node selected then auto call the lower level function to move vertically for the menu bar case? It would make the user API seemless.

I think your API makes sense, especially if you want to override the mouse movement for some other reasons.

Thanks for looking into this.

**Comment by brcolow** [comment]
I am working on this in the `issue-305` branch of my TestFX fork repository: https://github.com/brcolow/testfx/tree/issue-305 . Will open a PR when I am more satisfied with the approach. Comments welcome at this stage, though.

Currently the motion type is chosen transparently depending on the run-time type of the Node selected via the CSS selector (so in this case `#newItem` which has a run-time (simple name) of `MenuItemContainer`). Allowing the user to specify the method of motion is coming up in future work.

**Comment by brcolow** [comment]
Although there is still some cleaning up to do, and probably lint errors, I have opened a PR so that the work can be tracked more easily:

https://github.com/TestFX/TestFX/pull/363

**Comment by brcolow** [comment]
Fixed in https://github.com/TestFX/TestFX/pull/363
