### ISSUE TITLE
Functionality to clear TextFields

### ISSUE THREAD

**Issue by minisu** [TestFX/TestFX#31]
And similar controls. Using `push(KeyCode.BACK_SPACE)` in a loop is too ugly for such a common action.

Please let me know if you start working on this so we don't do double-work.

**Comment by RobzInadE** [comment]
I'm guessing this function `TextInputControls.clearText` has been moved to the legacy project? How do we accomplish the same thing in 4.0.x-alpha?

Regards

**Comment by marcin-chwedczuk** [comment]
I am using code like this:
```java
    private TextField control() {
        return robot
                .lookup(idSelector())
                .queryAs(TextField.class);
    }

    public TextFieldInspector setText(String text) {
        TextField control = control();

        Platform.runLater(() -> control.clear());
        WaitForAsyncUtils.waitForFxEvents();

        robot
                .clickOn(control(), MouseButton.PRIMARY)
                .write(text);

        return this;
    }
```
