### ISSUE TITLE
JUnit 5 Compatability

### ISSUE THREAD

**Issue by brcolow** [TestFX/TestFX#311]
Hello @hastebrot,

Given that [junit5](https://github.com/junit-team/junit5) is progressing quite well, have you considered adding compatibility with it to TestFX?

Thanks, let me know your thoughts.

**Comment by hastebrot** [comment]
I watched a presentation about JUnit 5 in a university in Vienna last month. The person giving the talk told me, that we can't reuse JUnit 4 classes like `@Rule`s in JUnit 5 and have to reimplement then.

I suggest to create a `testfx-junit5` module and implement a class that can be used with `@Extends`. Don't have enough spare time in the moment.

**Comment by raniejade** [comment]
Integration with [Spek](https://github.com/JetBrains/spek) would be nice as well. Any documentation on how to bootstrap TestFX?

**Comment by hastebrot** [comment]
@raniejade Here is a good starting point:

https://github.com/TestFX/TestFX/blob/7ab75cf6e5/subprojects/testfx-junit/src/main/java/org/testfx/framework/junit/ApplicationRule.java#L52-L59

**Comment by raniejade** [comment]
awesome, thanks @hastebrot.

**Comment by hastebrot** [comment]
I haven't used Spek in a while. But I guess there could be something like a subject for `Stage`s and `Application`s (sometimes you want to test whole applications, sometimes single stages).

**Comment by raniejade** [comment]
Yeah, I guess something along that line. We are currently working on extensions, I'll consider this use case.

**Comment by hastebrot** [comment]
Somehow I also really like the explicitness of something like

~~~kotlin
expect(scenes).to.have.label("test") // via: winterbe/expekt
assertThat(scenes, haveLabel("test)) // via: npryce/hamkrest
~~~

**Comment by brcolow** [comment]
Pull request for JUnit 5 support: https://github.com/TestFX/TestFX/pull/337

**Comment by brcolow** [comment]
Closed by: https://github.com/TestFX/TestFX/pull/337
