### ISSUE TITLE
TableView click

### ISSUE THREAD

**Issue by HYUNMIN-KIM** [TestFX/TestFX#336]
I want to click each tableview list.
for example
1 a
2 b
3 c
4 d
this is 4 rows table. 
I want to test click the 'a'
however,I can't click the tableview list value. help me please.

**Comment by jcornaz** [comment]
May I as why is this issue closed ?

Has it been done ? Was it already in ? Is it not feasible ? Would it cost too much investment to implement ?

It appears I need this feature too. And I would be interested to know if it is possible or not. If it's possible, I'd like to know how to do it. If it's not possible yet, I would be interested to contribute to add this feature.

Thanks in advance for your support

**Comment by jcornaz** [comment]
I want to (and it seems that @HYUNMIN-KIM, wanted the same) to be able simulate a clik on a row (or a cecll) in table view.

Let's say I have a TableView currently displaying the following :

| Col1  | Col2 |
| ----- | ---- |
| 1     | a    |
| 2     | b    |
| 3     | c    |
| 4     | d    |

In a test I want to click on the row '2b' or click on the cell 'b'

**Comment by jcornaz** [comment]
Hard to write code for that, as my question is : "How can i write such code?".

But here's something that would have done the trick if existing :

```java
@Test public void testClickOnTableViewRow(FxRobot robot) {
	robot.clickOn(robot.lookupTable("#tableId").lookupRow(hasContent("2", "b")));
}
```

**Comment by brcolow** [comment]
What about using the CSS selector class?

```java
clickOn(lookup("table-row-cell").query());
```

The CSS classes can be found in [modena.css](https://gist.github.com/maxd/63691840fc372f22f470).

**Comment by jcornaz** [comment]
Sorry, I don't understand. How could I chose to click on a specific row with this method ?

In my example, what code would you write to perform a click on the row 2 ?

**Comment by brcolow** [comment]
Maybe:

```java
clickOn(lookup("table-row-cell").nth(2).query());
```

Or you can use a match lambda:

```java
clickOn(lookup("table-row-cell").match((TableRow) row) -> row.something()).query());
```

It's a good idea to put the code in an IDE with intelligent completions to check the available method chaining options. I know our documentation is very lacking, so this is usually the best way to explore the API.

**Comment by jcornaz** [comment]
Indeed `clickOn(lookup(".table-row-cell").nth(1).query());` works. Thanks for the tip.

Still, do you think it would be worth to have a dedicated explicit method for that ?

**Comment by brcolow** [comment]
I am not sure. I wouldn't be necessarily opposed to it. Depends on how well it fit in with the rest of the API. PR very much welcome.

**Comment by jcornaz** [comment]
Ok. Thanks for the help.

**Comment by dane15** [comment]
Any other possible way?

**Comment by scotNZ** [comment]
The way I manage this is through the interact() method to invoke on the FX Thread. This way you have access to all the normal methods of interaction available from JavaFx.

TableView tableView = (TableView)find("#some-table-ref");
interact(() -> {
	tableView.getSelectionModel().selectLast();
});

**Comment by xcruel** [comment]
Hi!
Im trying to click on a row too, i want to try this:
`clickOn(lookup(".table-row-cell").nth(1).query());`
but what is that i lookup? What is ".table-row-cell"?
What am i supposed to write in lookup, the table's name?

**Comment by 1504168** [comment]
Just wanted to let anyone know if you are facing problem on finding node using nth(rowNumber).query then try to use Thread.Sleep before finding the node. 
![Node Finding Problem TestFX](https://user-images.githubusercontent.com/31016570/138213901-5f0826c8-6dc3-4f4c-a34e-d0c6da079f66.png)
but if i use Thread.Sleep(1000) then it doesn't throw any error.
