### ISSUE TITLE
Java 9 support?

### ISSUE THREAD

**Issue by tbee** [TestFX/TestFX#356]
The JavaFX team has asked framework developers to start testing with Java 9. JFXtras uses TestFX 3, so I want to first upgrade to TestFX 4. But does TextFX 4 work under Java 9?

And is there a good example of how a test should look under 4? Because after including 4.0.5-alpha in my gradle script, I do not have an ApplictionTest class (as is shown in the example on github).

**Comment by tbee** [comment]
I think the mistake may be that in the example on GitHub testfx-legacy is included with junit excluded, I suspect that should have been textfx-junit.

**Comment by brcolow** [comment]
If you want to use TestFX 4 the first example should be used:

```java
repositories {
    jcenter()
}

dependencies {
    testCompile "org.testfx:testfx-core:4.0.5"
    testCompile "org.testfx:testfx-junit:4.0.5"
}
```

You should be able to freely substitute `jcenter()` with `mavenCentral()`.

With these dependencies you will have `ApplicationTest` which will allow you to easily create tests like the first code example in the README.

Java 9 support is currently being worked on in https://github.com/TestFX/TestFX/issues/228.

Maybe the README should more clearly delineate which dependencies should be declared for TestFX 4 and which should be declared for TestFX 3.

**Comment by tbee** [comment]
At least it was confusing enough for me. But I'm tagging along fine now, migration is on its way.
