### ISSUE TITLE
`Push(KeyEvent.CONTEXT_MENU)` does not produce system-independent context menu request event

### ISSUE THREAD

**Issue by JordanMartinez** [TestFX/TestFX#374]
Using the `0.4.5-alpha` release, I have a simple test:

````java
clickOn(area);
push(KeyCode.CONTEXT_MENU);
assertThat(area.getContextMenu().isShowing());
````

This test fails. When I added `println` statements to its `onKey[Pressed/Released/Typed]` properties, only the released handler is called.

Since I saw that you are switching to `Event.fireEvent` to produce events, this may have already been fixed in the master branch.

**Comment by brcolow** [comment]
Would you have time to test this against master branch? If not I will sooner than later :).

**Comment by JordanMartinez** [comment]
I'm testing it right now.

**Comment by JordanMartinez** [comment]
Nope. It fails. Tested using JUnit4-version of TestFX with the following test:
````java
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.MenuItem;
import javafx.scene.input.KeyCode;
import javafx.stage.Stage;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class ContextTest extends ApplicationTest {

    private TextArea area;

    @Override
    public void start(Stage stage) throws Exception {
        area = new TextArea("some text");
        ContextMenu menu = new ContextMenu(new MenuItem("a menu item"));
        area.setContextMenu(menu);
        stage.setScene(new Scene(area, 500, 500));
        stage.show();
    }

    @Test
    public void testContextMenu() {
        clickOn(area);
        push(KeyCode.CONTEXT_MENU);

        assertTrue(area.getContextMenu().isShowing());
    }
}
````

**Comment by brcolow** [comment]
I am not familiar with `KeyCode.CONTEXT_MENU`. The Javadocs say:

`Constant for the Microsoft Windows Context Menu key.`

But your issue mentions `system independent`? Sorry to be so pedantic but which key are you expecting to be pressed for which OS?

**Comment by JordanMartinez** [comment]
Sorry, that should not have been in the original comment as the javadoc
says it's only for Windows (it's been a while since I wrote the code so I
forgot that).

The affected test only runs when built on a Windows OS. Via
ContextMenuEvent's javadoc, the keys pressed should be `Shift + F10` but
the Context key code is more readable.


On Mar 21, 2017 5:00 PM, "Michael Ennen" <notifications@github.com> wrote:

I am not familiar with KeyCode.CONTEXT_MENU. The Javadocs say:

Constant for the Microsoft Windows Context Menu key.

But your issue mentions system independent? Sorry to be so pedantic but
which key are you expecting to be pressed for which OS?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TestFX/TestFX/issues/374#issuecomment-288257084>, or mute
the thread

**Comment by brcolow** [comment]
I edited my above comment and added that the above unit test passes for me on Windows 10 with latest master, so I am not sure how to proceed.

**Comment by JordanMartinez** [comment]
\*facepalm\* 

Well, that's probably because I ran it on a Linux environment :sweat_smile:, hahaha! Sorry! I'm glad it's fixed in the master branch though.
