### ISSUE TITLE
Publish a new version to a maven repository

### ISSUE THREAD

**Issue by feanor12** [TestFX/TestFX#375]
A new SNAPSHOT of the project is needed to build PlayOnLinux5. The issue(PlayOnLinux/POL-POM-5#673) would be fixed it we could add the latest SNAPSHOT to our build. I now there is a repository for snapshots(https://oss.sonatype.org/content/repositories/snapshots/), but it seems outdated. Please update it.

**Comment by brcolow** [comment]
`4.0.6-alpha` has just been released. It should sync to maven central within a couple days. The snapshot repository is outdated and since we are in alpha anyways it makes more sense just to issue a real release.

**Comment by brcolow** [comment]
4.0.6-alpha is now synced to maven central.
