### ISSUE TITLE
TableViewMatchers use underlying value, not rendered text

### ISSUE THREAD

**Issue by adamish** [TestFX/TestFX#378]
If you use a cell factory to change how a value is displayed, e.g. decimal formatting... see http://stackoverflow.com/a/43000195/898289....

then matchers such as hasCellValue or hasTableCell only test for the actual value, not how it is rendered. For example the value might be a double with value 0.11111111234, but it is rendered as "0.11"... and this is what I wish to test.

Great project by the way.

I've kind of worked around this my creating my own matcher

   public static Matcher<Set<Node>> hasTableText(String value) {
        return new BaseMatcher<Set<Node>>() {
            @Override
            public void describeTo(Description description) {
                // not used
            }

            @Override
            public boolean matches(Object item) {
                Set<Node> nodes = (Set<Node>) item;
                for (Node node : nodes) {
                    if (node instanceof TableCell<?, ?>) {
                        String text = ((TableCell<?, ?>) node).getText();
                        if (text != null && text.contains(value)) {
                            return true;
                        }
                    }
                }
                return false;
            }
        };
    }

**Comment by brcolow** [comment]
Thanks very much for the report, working on this in https://github.com/TestFX/TestFX/pull/379.

**Comment by brcolow** [comment]
#379 is now in a passing state @adamish - would you mind taking a look and making sure it is satisfactory for your request? Thanks!
