### ISSUE TITLE
FXAssert.verifyThat unstable? (Version 4.0.6-alpha)

### ISSUE THREAD

**Issue by mayuso** [TestFX/TestFX#384]
I am trying to do a couple simple tests:

    fx.clickOn("#languageChangeButton1");
    verifyThat("#myLabel", NodeMatchers.hasText("MyText"));

I do this 3 times, each time I press a different button: languageChangeButton1, languageChangeButton2 and languageChangeButton3, and compare the label value to "MyText", which is different for each language.

**It always works well with one of the buttons, but always fails with the other 2.** I don't know why, this is the log in the 2 problems:

    Expected: Node has text "MyText:"
         but: was <Label[id=myLabel, styleClass=label]'MyText'>

AFAIK what's happening is that the `verifyThat` function is not returning the label text properly, right?

Am I doing something wrong or is it a bug? 

Sorry for wasting your time.

Thank you.

**Comment by brcolow** [comment]
Can you please show the code for the entire test so I can play around with it? Thanks!

**Comment by hastebrot** [comment]
@mayuso 

The text of the node is indeed different to the expected value (notice the colon at the end):

~~~diff
-MyText:
+MyText
~~~

**Comment by mayuso** [comment]
@brcolow I am afraid I can't, I don't legally own the code, sorry.

@hastebrot You are right, but that was a typo. As you can imagine, "MyText" and "MyText:" are not the real text values, I just used them as an example, the actual values are equal.


I am somehow trapped by the fact that I can't show the code. I'll keep testing and see if I can 100% reproduce the problem in another custom example case that I can show.

**Comment by mayuso** [comment]
*Update:* Literally 15 minutes later I found the problem. And I owe you all an apology, it was totally my fault.

I was trying to compare "Create dossier" to "Create Dossier" (Yes, these are the actual real texts (inside a button)).

I am sorry.

**Comment by brcolow** [comment]
No worries! Glad you got it figured out.
