### ISSUE TITLE
Licence links missing ".html" suffix

### ISSUE THREAD

**Issue by nickthecoder** [TestFX/TestFX#391]
The link to the licence on your main git hub page (https://github.com/TestFX/TestFX) is broken. It is missing the ".html" suffix :

http://ec.europa.eu/idabc/eupl 

It should read

http://ec.europa.eu/idabc/eupl.html

It is also similarly broken within the headers of your source code. e.g.
https://github.com/TestFX/TestFX/blob/master/subprojects/testfx-core/src/main/java/org/testfx/api/FxAssert.java

**Comment by brcolow** [comment]
Thanks for the heads up - I'll try and get to this soon. PR welcome in the meantime of course :)!

**Comment by hastebrot** [comment]
I guess, they changed to URL a while ago; it worked without `.html` suffix a while ago:#

https://web-beta.archive.org/web/20100416172850/http://ec.europa.eu:80/idabc/eupl
