### ISSUE TITLE
How to wait for Element?

### ISSUE THREAD

**Issue by eiswind** [TestFX/TestFX#392]
Forgive me that I'm very new to testfx. I just wonder how I can safely wait for an element to appear? The examples are very sparse here.

**Comment by brcolow** [comment]
Take a look at [WaitForAsyncUtils#waitFor(..)](https://github.com/TestFX/TestFX/blob/master/subprojects/testfx-core/src/main/java/org/testfx/util/WaitForAsyncUtils.java#L297) as well as the waitForFxEvents methods also in WaitForAsyncUtils. WaitForAsyncUtils will most likely be integrated into the `FxRobot` interface as the functionality it provides is really central to JavaFX GUI testing.

**Comment by eiswind** [comment]
robot.lookup("#exit").tryQuery<Node>().isPresent()

is this how one would do it? At least it works! Thanks for the hint.

**Comment by brcolow** [comment]
We need to improve our documentation, but I think this issue can be closed for now.
