### ISSUE TITLE
Cant Lookup MenuItem on OSX

### ISSUE THREAD

**Issue by nartz** [TestFX/TestFX#398]
Hi - 

On OSX - the menubar is at the top of the screen with JavaFX. It doesn't seem to find the top or nested level menu items, such as 'file' or for File > "Log in" it doesn't find login. I assume its because they dont sublcass 'Node'. Both of these error:

robot.lookup("File")
robot.lookup("Log In")
robot.lookup("#logInMenuItem")

I can look these up more 'manually' i.e. traversing the objects from the MenuBar, but then, how can I actually 'click' on them? Robot seems to need a 'Node' object, which these can't be cast to. 

Thanks.
I'm using 4.0.6-alpha on Java 8 on OSX.

**Comment by brcolow** [comment]
Are you using `setUseSystemMenuBar(true)` on your menu bar that you are testing? Could you perhaps provide a code example so I have something to work with? Thanks.

**Comment by nartz** [comment]
Ah yes - we are using setUseSystemMenuBar(true) - I assume that TestFx then
can't access these because they are system native?

**Comment by brcolow** [comment]
Yes I believe that is what the issue is. I am not sure if there is any way to remedy this.

**Comment by JordanMartinez** [comment]
I know very little about this, so this may be way off topic. However, `PrimaryStageApplication` uses `StageStyle.UNDECORATED`. Would that have any implications in this matter?

**Comment by nartz** [comment]
I chose to just do...

if (!isDevelopmentEnv()) {
    menuBar.setUseSystemMenuBar(true);
}

Thanks!
