### ISSUE TITLE
ListView UI Rendering Delay issue with WaitUntilSupport

### ISSUE THREAD

**Issue by nartz** [TestFX/TestFX#403]
Hi - 
I am adding an item to a listview and then clicking on that item. I'm trying to use WaitUntilSupport to wait until that item has been added to the list, and then click on it.

I currently have a listview that is bound to a list of strings, i.e. myListView.setItems(myList). When I add something to the list itself, there is a minor delay between when the item is added to the list (i.e. there is a short time period myListView.getItems() is 1, while in the UI nothing appears in the listview), and when the pdf list view is rendered on the screen.

I'm trying to figure out the right way to use WaitUntilSupport to 'wait' until the item in the list view is visible from a users standpoint in the ListView. Are there any suggestions? I see the ListView matchers actually just call .getItems() etc internally, so I'm not sure those will work. Here are a few attempts:

waitUntilSupport.waitUntil(robot.from(myListViewNode).lookup("MyListViewText").query(), isNotNull()) //unfortunately this returns a NullPointerException because the node isn't yet available
//also, since the elemtn isn't rendered yet i assume isVisible() will not work...

waitUntilSupport.waitUntil( { robot.from(myListViewNode).lookup("MyListViewText").query() }, isNotNull()) //this seems to work I believe, the 'brackets' are actually groovy syntax for making that a callable object

Thanks.

**Comment by brcolow** [comment]
Sorry for the brief response but take a look at `WaitForAsyncUtils.waitFor(long timeout, TimeUnit timeUnit, Callable<Boolean> condition)`, something like:

```java

public void test() throws Exception {
  myList.add(someItem);
  WaitForAsyncUtils.waitFor(5, TimeUnit.SECONDS, () -> robot.from(myListViewNode).lookup("MyListViewText").query() != null));
  // assert something
}
```
