### ISSUE TITLE
TestFx and pause/wait

### ISSUE THREAD

**Issue by HerbertKoelman** [TestFX/TestFX#419]
Is there a way to preventing TestFX from immediately exiting ? 

I'd like to test a message driven UI. In fact I display TableView that is populated with data that are received through JMS.

Therefore I'd like to prevent my UI to be closed and give it some time to wait for a message to arrive.

Is there such a thing as "pause" or "wait"

**Comment by JordanMartinez** [comment]
Couldn't you use `ApplicationTest#stop` to run code before completely exiting? If you're testing your own Application, that's a different matter.

**Comment by HerbertKoelman** [comment]
@JordanMartinez I'm indeed test my own application. I guess I'll have to find an other way to go :-)
