### ISSUE TITLE
TableViews.row() breaks after some time

### ISSUE THREAD

**Issue by Philipp91** [TestFX/TestFX#42]
The JavaFX TableViewSkin implementation (at least in Java8) makes use of the possibility to "reuse" row and cell objects, which causes to appear (on the UI) in a different order than they have in the scene graph. I haven't prepared an example to reproduce this, but it should be pretty clear, that the current implementation of TableViews.row() cannot work (I was too quick on that :-)). In my own application, the problem occurs after only two or three content changes: Everything is in order, except the first row is at the very end in the scene graph.

The same problem might occur in ListViews.

**Comment by brcolow** [comment]
This is an issue about the deprecated, legacy version of TestFX.
