### ISSUE TITLE
FxRobot: clickOn(Node, MouseButton...) moves cursor to wrong location

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [TestFX/TestFX#430]
This method usually works fine as it moves the cursor to the center of the Node (see video below, note the position of the cursor is moved to the center of each of the container boxes).

![2017-09-20 22 48 35](https://user-images.githubusercontent.com/19281514/30651204-9be36df2-9e57-11e7-9588-e0ce21f4b14f.gif)

However, on certain computers, the cursor is moved to the wrong location (see video below, ignore the pop ups in the video). This causes test cases to fail when they are run on these computers.

![helpwindowtest](https://user-images.githubusercontent.com/1673303/30570248-9eb24558-9d12-11e7-8ddd-3359688f4662.gif)
(Just before the test fails: The cursor is supposed to click inside the container box at the bottom right. However, it stops short of the container box.)

Further info: I've tested on 2 Windows 10 computers and this method does not function correctly only on 1 of them. Works fine on the Mac I'm using, though I'm not sure if it works for all other Macs as well.

**Comment by brcolow** [comment]
Could you provide a failing test case?

**Comment by Zhiyuan-Amos** [comment]
Hello, thanks for your reply! Sorry that I haven't been clear in my explanation.

In the first video, the cursor moves to the center of the bottom-left container (The box containing the name `Benson Meier`) and clicks on it, before moving horizontally to the right to the center of the bottom-right container and clicks on it.

However, in the second video, the cursor does not move to the right to the center of the bottom-right container. It stops short of it. As such, the cursor is still clicking on the bottom-left container. This causes the test in my application to fail.

**Comment by brcolow** [comment]
I should have been more clear myself - what I mean is could you post the code of a reproducible test-case [like this](https://github.com/TestFX/TestFX/blob/master/subprojects/testfx-core/src/test/java/org/testfx/cases/integration/MenuBarTest.java). That is the easiest way for me to investigate.

**Comment by Zhiyuan-Amos** [comment]
Here's the [Test](https://github.com/se-edu/addressbook-level4/blob/master/src/test/java/guitests/HelpWindowTest.java)!

**Comment by brcolow** [comment]
Unfortunately that is not very useful because that test references many custom classes with lot's of logic. What I meant by "reproducible" is that it is a self-contained, minimal test where only standard JavaFX controls are used. Otherwise it is very hard and will take much time to figure out the root cause.

**Comment by Aidamina** [comment]
Could this be related to https://github.com/TestFX/TestFX/issues/245

**Comment by Zhiyuan-Amos** [comment]
I will close this issue as the Windows 10 PC passes the test even at different scale settings. I'm not quite sure why this issue seems to auto-resolve on its own though.

**Comment by Aidamina** [comment]
@Zhiyuan-Amos Are you running Java 9? Because that might be the cause for it fixing itself automatically.
