### ISSUE TITLE
5 test failed

### ISSUE THREAD

**Issue by LukeARohl** [TestFX/TestFX#431]
cloned the master, ran gradle clean, then gradle build. When gradle build was run these 5 tests failed. Mac verision 10.12.6
[test.zip](https://github.com/TestFX/TestFX/files/1330158/test.zip)

ShortcutKeyTest. shortcut_keyCode_converts_to_OS_specific_keyCode_when_pressed
ShortcutKeyTest. shortcut_keyCode_converts_to_OS_specific_keyCode_when_released
AwtRobotAdapterTest. getCapturePixelColor
AwtRobotAdapterTest. getCaptureRegion
GlassRobotAdapterTest. getCaptureRegion

**Comment by Tristan971** [comment]
Same result here (Java 8, macOS 10.13)

**Comment by Oliver-Loeffler** [comment]
Hi, I was able to reproduce this in OS X and Windows too. 
@JordanMartinez started already issue #411 to deflake these tests.

Related issues are: #436 and #435

**Comment by Oliver-Loeffler** [comment]
The above mentioned tests I only could reproduce with macOS, not on windows. My mistake.
But at least for the getCapture() tests I learned about the mechanism, its related to color correction on macOS.

**Comment by brcolow** [comment]
Covered by other issues.
