### ISSUE TITLE
Question: how to use TestFX with Java9 and Maven

### ISSUE THREAD

**Issue by Oliver-Loeffler** [TestFX/TestFX#433]
Hi TestFX team!

While playing around with TestFX I just started to discover Java9 JPMS. JPMS alone works great, TestFX with Java8 is awesome. However, I was not able to combine both - so the question is: is there already any way to use TestFX with Java9?

I have some tests in Java8, migrated the project to Java9 but tests are no longer working.  Each GUI test aborts with a failure in calling `javafx.stage.Window.impl_getWindows()Ljava/util/Iterator;`, the question is, is that due to the wrong way of test execution or setup or is TestFX just not yet Java9 compatible?

I am using maven 3.5.0 for build with Java SE build 9+181 on macOS Sierra - I'll try this also on Windows, just to see if the platform makes a difference. 

Here I set .mvn/jvm.config with following params:
```
--illegal-access=warn --add-opens  javafx.graphics/javafx.stage=ALL-UNNAMED
```

Furthermore I've added `--add-reads` or `--add-exports` as compiler arguments but those did not help to get TestFX running. Also I tried to pass `--add-opens` to the compiler using `-J`.
I guess I'm making a fundamental error here.

The stack trace looks as follows:
```
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 3.487 sec <<< FAILURE!
captureRearrangedTabs(net.raumzeitfalle.fxsamples.pocketcalculator.ApplicationViewTest)  Time elapsed: 2.17 sec  <<< ERROR!
java.lang.NoSuchMethodError: javafx.stage.Window.impl_getWindows()Ljava/util/Iterator;
	at org.testfx.service.finder.impl.WindowFinderImpl.fetchWindowsInQueue(WindowFinderImpl.java:141)
	at org.testfx.service.finder.impl.WindowFinderImpl.fetchWindowsByProximityTo(WindowFinderImpl.java:146)
	at org.testfx.service.finder.impl.WindowFinderImpl.listTargetWindows(WindowFinderImpl.java:71)
	at org.testfx.service.finder.impl.NodeFinderImpl.rootsOfWindows(NodeFinderImpl.java:115)
	at org.testfx.service.finder.impl.NodeFinderImpl.fromAll(NodeFinderImpl.java:77)
	at org.testfx.service.finder.impl.NodeFinderImpl.lookup(NodeFinderImpl.java:62)
	at org.testfx.api.FxRobot.lookup(FxRobot.java:213)
	at net.raumzeitfalle.fxsamples.pocketcalculator.ApplicationViewTest.captureRearrangedTabs(ApplicationViewTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
```

What is the technical intended and correct way to setup TestFX with JDK9 and JPMS?
If there is no defined way yet or an example, when I get this running I'd prepare a wiki page summarizing the outcome so that there would be the a TestFX + Java9 + Maven example.

Thanks a lot!

For reference (if needed):
POM  https://github.com/Oliver-Loeffler/FXSamples/blob/master/pom.xml

A failing test (NoSuchMethodException):
https://github.com/Oliver-Loeffler/FXSamples/blob/master/src/test/java/net/raumzeitfalle/fxsamples/pocketcalculator/ApplicationViewTest.java

**Comment by JordanMartinez** [comment]
> is there already any way to use TestFX with Java9?

Yes. I'm not sure whether there is a release that includes it. You can, however, build it yourself and use that locally-compiled version for it work. You must compile it using Java 9.

**Comment by Oliver-Loeffler** [comment]
Thanks, I'm going to try that again. Just stopped there today as there were a few failing tests. I'll let you know if it worked out.

**Comment by Oliver-Loeffler** [comment]
It indeed works w/o issues and w/o additional classpath / modulepath settings. The only point was that I had to run the Gradle build with setting `test {  ignoreFailures = true }` as some tests involving lambdas in setOnAction did not pass.

**Comment by Oliver-Loeffler** [comment]
I'll summarize the tests w/  issues but so far my question is answered. Thanks @JordanMartinez.

**Comment by JordanMartinez** [comment]
Glad it helped.

**Comment by Oliver-Loeffler** [comment]
Do you track failing tests also in Github issues? Does it make sense to report them here? I tested on Linux, Windows and OSX. I'm still not familiar enough with the project code to make significant contributions but if its helpful I'd start with those little things.

**Comment by JordanMartinez** [comment]
I don't see why not. We could do it in a PR, but that usually means the person submitting it is going to fix it. If you report it, you'll letting the contributors know, and they can further work it out there.

**Comment by danlangford** [comment]
for the record i was able to get it java9 tests working without a local recompile by just playing with my POM a little bit

```
    <dependency>
      <groupId>org.testfx</groupId>
      <artifactId>testfx-core</artifactId>
      <version>${testfx.version}</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.testfx</groupId>
          <artifactId>testfx-internal-java8</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.testfx</groupId>
      <artifactId>testfx-internal-java9</artifactId>
      <version>${testfx.version}</version>
      <scope>test</scope>
    </dependency>
```

**Comment by brcolow** [comment]
I am unhappy with the way things currently are. Local recompiles and POM exclusions should be unnecessary.  I will do some reading and hopefully come up with a better way forward.

**Comment by danlangford** [comment]
Instead of having testfx-core depend on testfx-internal-java8 maybe you could have a testfx-java8 and a separate testfx-java9 both depend on testfx-core or -common or something.

**Comment by brcolow** [comment]
That sounds like a much more reasonable approach, I will experiment with that. Good idea.

**Comment by AdamCarroll** [comment]
It you're interested in trying out the solution from @danlangford in Gradle, it would look something like this:
```gradle
testCompile('org.testfx:testfx-core:4.0.8-alpha') {
    exclude group: 'org.testfx', module: 'testfx-internal-java8'
}
testRuntime 'org.testfx:testfx-internal-java9:4.0.8-alpha'
```
You can see it applied on the experimental JDK 9 branch of VocabHunter here: https://github.com/VocabHunter/VocabHunter/commit/b2326e3bb12b4c8582ee6f86fb6834fab170feda

**Comment by AdamCarroll** [comment]
On a related note, for headless testing on JDK 9 with Gradle you will need to replace your Monocle depenency.  If you have something like this:
```gradle
testRuntime 'org.jfxtras:openjfx-monocle:1.8.0_20'
```
You will need to replace it with something like this:
```gradle
testRuntime 'org.testfx:openjfx-monocle:jdk-9+181'
```
Again, you can see it applied in the experimental JDK 8 branch of VocabHunter: https://github.com/VocabHunter/VocabHunter/commit/5034fc568efa058274eeaedfc80118c61daa60c4

My article [User Interface Testing with TestFX](https://vocabhunter.github.io/2016/07/27/TestFX.html) includes more details on getting headless testing to work.

**Comment by AdamCarroll** [comment]
A possible way to handle this in Gradle is to switch dependencies according to the JDK version at build time, as per [this gist](https://gist.github.com/AdamCarroll/81ce8322924bcde4cf79d6691c71b927).  I'm not sure how that could be done in Maven though.

**Comment by winterer** [comment]
@brcolow - maybe you could use maven profiles in your `testfx-core` pom to either include `testfx-internal-java8` or `testfx-internal-java9`. Profile activation could be done via jdk-version.

I've never done this, but it should work accoring to the documentation (http://maven.apache.org/guides/introduction/introduction-to-profiles.html).

**Comment by carltonwhitehead** [comment]
Thanks for the suggestion @winterer. I managed to get this working on my project with the profiles section below. My tests are now running properly on JDK 8 and 9.

IntelliJ users, after setting your Project SDK to 9, also make sure to open your `Maven Project` window and tick the box for `jdk9` profile. Mine didn't pick it up automatically, and I kept getting the same stack trace whenever I ran my JUnit tests via IntelliJ.

```xml
    <profiles>
        <profile>
            <id>jdk9</id>
            <activation>
                <jdk>9</jdk>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>org.testfx</groupId>
                    <artifactId>testfx-core</artifactId>
                    <version>${testfx.version}</version>
                    <scope>test</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>org.testfx</groupId>
                            <artifactId>testfx-internal-java8</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>org.testfx</groupId>
                    <artifactId>testfx-internal-java9</artifactId>
                    <version>${testfx.version}</version>
                    <scope>test</scope>
                </dependency>

                <dependency>
                    <groupId>org.testfx</groupId>
                    <artifactId>openjfx-monocle</artifactId>
                    <version>jdk-9+181</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>jdk8</id>
            <activation>
                <jdk>1.8</jdk>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>org.testfx</groupId>
                    <artifactId>testfx-core</artifactId>
                    <version>${testfx.version}</version>
                    <scope>test</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>org.testfx</groupId>
                            <artifactId>testfx-internal-java9</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>org.testfx</groupId>
                    <artifactId>testfx-internal-java8</artifactId>
                    <version>${testfx.version}</version>
                    <scope>test</scope>
                </dependency>

                <dependency>
                    <groupId>org.testfx</groupId>
                    <artifactId>openjfx-monocle</artifactId>
                    <version>8u76-b04</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
```

**Comment by brcolow** [comment]
Documented in the README. Exclusions are less than ideal, though.
