### ISSUE TITLE
Build on Windows is not reapatable (single subproject check passes, any repeat will fail)

### ISSUE THREAD

**Issue by Oliver-Loeffler** [TestFX/TestFX#435]
### Consecutive execution of tests will cause test failure on Windows 8.1 6.3 amd64

On Windows 8.1 (6.3 amd64) with Java9+181 (and Java 1.8u144) its not possible to get a successful build of TestFX from scratch. Gradle version used: Gradle 4.1 (distribution and wrapper, both tested) 2017-08-07 14:38:48 UTC

There failing tests in subprojects: *testfx-core*, *testfx-junit* and *testfx-junit5* 
Following tests are affected:

**testfx-core**
`org.testfx.cases.acceptance.FxAssertBasicTest.button_has_label()`

**testfx-junit**
`org.testfx.cases.acceptance.ApplicationLaunchTest.should_click_on_button()`

**testfx-junit5**
`org.testfx.cases.acceptance.ApplicationLaunchTest.should_click_on_button()`

### How to reproduce:
 1. login 
 2. open CMD command line (or git bash)
 3. change dir into subproject (e.g. testfx-core)
 4. run either `gradlew clean check` or run `gradle clean check`
 5. all tests will pass with the first execution
 6. repeat execution using either `gradlew clean check` or `gradle clean check`
   * Result will be one failing test (one of the above mentioned).

Running the main build script will also show this error mode.
 1. from TestFX project root directory run `gradlew clean check`
 2. subproject **testfx-core** is built and will pass all tests in check task
 3. subproject **testfx-junit** is built and check task is executed
   * Test will fail: `org.testfx.cases.acceptance.ApplicationLaunchTest.should_click_on_button()`

Restarting the build script with `gradlew clean check` from TestFX root will cause following result:

 * Test failed `org.testfx.cases.acceptance.FxAssertBasicTest.button_has_label()` (1 failure out of 330 tests, 27 skipped)

As a next step, for *testfx-core* and *testfx-junit* the property `ignoreFailures` can be set to `true`.
Another execution of `gradlew clean check` will create the following result:

The only failing tests are:
 **testfx-core** ->  `org.testfx.cases.acceptance.FxAssertBasicTest.button_has_label()` 
 **testfx-junit** ->  `org.testfx.cases.acceptance.ApplicationLaunchTest.should_click_on_button()` 

So far, on Windows 8.1, the only option to recover is to logout user and to login again.
The to build all sub projects the way is:
 1. login
 2. build one subproject
 3. logout
 4. login 
 5. build next subproject
 6. logout and so on...

So the build process is not repeatable. 
This behavior was not reproducible on Mac OS Sierra 10.12.6 (with identical JRE and Gradle versions).

**Comment by JordanMartinez** [comment]
I think these tests are known to be flaky. Check the latest AppVeyor builds to see for yourself.

**Comment by Oliver-Loeffler** [comment]
Okay, I see, there is even an issue "deflake flaky tests". I'll look into. But what I was wondering, they pass first, which is fine, but something remains changed. Then, even after JVM termination and restart the tests will fail, which is strange. I'll continue reading.

**Comment by JordanMartinez** [comment]
ah.... that is interesting...

**Comment by Oliver-Loeffler** [comment]
This is confusing. I just killed all JVMs running. Then I just ran a check of **testfx-junit** and it passes (no clean). Then I tried it 2 more times, all pass. 

After that I ran `gradle check`on **testfx-junit5** with 100% pass, same then also on **testfx-core**, 100% pass rate. Even running now `gradle build` from TestFX root works fine (!) after killing the JVMs left over from the first failing attempts. 

So the sequence for a proper build (on my system) would be:
 1. run `gradle build` first time -> have all flaky tests failing
 2. kill all JVMs manually
 3. run `gradle build` as often as you like ... it works.

Now even after logoff/logon it continued to work flawlessly. So i tried a system restart. Now the tests again are failing. I'm not able to reproduce the state where the tests were passing.

This is truly confusing.

**Comment by Oliver-Loeffler** [comment]
PR #438 solves this issue (at least on Windows 8.1) but behavior is assumed to be identical on Windows 7 and Windows 10.

**Comment by Oliver-Loeffler** [comment]
PR #438 solves this issue (at least on Windows 8.1) but behavior is assumed to be identical on Windows 7 and Windows 10.

**Comment by Oliver-Loeffler** [comment]
PR #438 merged.
