### ISSUE TITLE
Build of testfx-core on Mac OS Sierra 10.12.6 fails

### ISSUE THREAD

**Issue by Oliver-Loeffler** [TestFX/TestFX#436]
When trying to build TestFX on Mac OS Sierra 10.12.6, the build will fail due to failing tests in **testfx-core** subproject.

Following tests are affected:
 * ShortcutKeyTest
```
org.testfx.robot.impl.ShortcutKeyTest
   .shortcut_keyCode_converts_to_OS_specific_keyCode_when_pressed(ShortcutKeyTest.java:107)

org.testfx.robot.impl.ShortcutKeyTest
   .shortcut_keyCode_converts_to_OS_specific_keyCode_when_released(ShortcutKeyTest.java:116)
```

 * AwtRobotAdapterTest
```
org.testfx.service.adapter.impl
   .AwtRobotAdapterTest.getCapturePixelColor(AwtRobotAdapterTest.java:260)

org.testfx.service.adapter.impl
   .AwtRobotAdapterTest.getCaptureRegion(AwtRobotAdapterTest.java:275)
```
 * GlassRobotAdapterTest
```org.testfx.service.adapter.impl.GlassRobotAdapterTest
   .getCaptureRegion(GlassRobotAdapterTest.java:274)
```

Subprojects **testfx-junit** and **testfx-junit5** are passing all checks.

**Comment by Oliver-Loeffler** [comment]
See #411, #431, #435.

**Comment by Oliver-Loeffler** [comment]
I have some news regarding the failing `GlassRobotAdapterTest` and `AwtRobotAdapterTest` classes. It seems that this issue on macOS 10.12.6 in conjunction with JDK9 is related to color management.

The idea is, when a component with a color "#abcdef" is drawn on screen, a capture of this colored region should still have the same color when tested. Of course, when color management is used, the value actually drawn to the screen might be different, so there are in fact somewhere at least 2 color values.

Now, I wrote a small test where the region color is modified from (e.g.)  `Color.rgb(0,0,0)` to `Color.rgb(255,255,255)` or to `Color.rgb(0,255,0)`. Lets call the desired region color value "input" and the color value of the tested pixel "captured". Now the input value vs. the captured value can be compared, per color channel (e.g. only comparing the red component). So it's now possible to plot input-red vs. captured-red and input-(green, blue) versus captured-(green,blue).

On Windows 8.1, this turns basically into a straight line drawn from (input, captured) -> (0,0) to (255,255). I was able to verify this for multiple color profiles (self calibrated, manually calibrated, vendor provided). There are variations in range of +/- 1/256ths. 
Please have a look on the following graph:

![colorcaptureawt_inputvscaptured_windows81_srgb](https://user-images.githubusercontent.com/22102800/31321794-77faa9c2-ac8b-11e7-8dee-9ec5b7b22190.png)

For macOS it looks completely different (well I've disabled night shift and flux). It's hard to see but the profiles Color-LCD (which was default) and sRGB-IEC61966-2.1 provide different colors. Interestingly ProPhoto RGB is just straight with an offset, whereas Color-LCD and sRGB profiles have a curvature.

![colorcaptureawt_inputvscaptured_osx_srgb_lcd](https://user-images.githubusercontent.com/22102800/31321506-6f518646-ac87-11e7-8368-e86ded8e52a4.png)

The following graph shows only the difference of the "captured" pixcel color channel value to the "input" color channel value.

![colorcaptureawt_inputvscaptured_osx_diffscapture2input](https://user-images.githubusercontent.com/22102800/31321521-c25638aa-ac87-11e7-97a4-6401c5ac731a.png)

Just to summarize the findings:
1. on Windows 8.1, all "color capture" tests work fine, no matter if color management is enabled/disabled
2. on Windows 8.1, color managament seems to be applied to JavaFX correctly (I tested that with 2 monitors simultaneously)
3. on macOS 10.12.6 all "color capture" tests fail due to a slightly incorrect captured color
4. on macOS 10.12.6 the colors captured by Awt and Glass robots depends on color profile settings

It can also be related to the macOS vs. Windows difference in gamma value setting - if this is still the case.
Are there any hooks in JavaFX, AWT to deal with system color management? Or is this a bug on JVM/JRE or even macOS level?

My expectation is, that regardless of gamma setting, regardless of color calibration, when a certain color is written to screen, readingt from video memory should result in same color value. The calibration should only be "visible" to human eye and not change the data.

You can use following Gists to reproduce this.
https://gist.github.com/Oliver-Loeffler/40dbc214155e9efcbe50c0dca4007a7e

I'm really curious, if this is reproducible.

**Comment by brcolow** [comment]
Is this only on JDK 9 or does 8 behave the same way?

**Comment by Oliver-Loeffler** [comment]
Here JDK9 (build 9+181) and JDK8 (8u144) behave the same way. No difference for the JDKs.
However, I tested JDK9 from commanding with `gradle check` and JDK8 from within eclipse running the build task.

**Comment by Oliver-Loeffler** [comment]
@brcolow @JordanMartinez Have you been able to reproduce it? 
How to continue here, any ideas?

**Comment by brcolow** [comment]
I will investigate within the next couple days. Sorry for the wait.

**Comment by Oliver-Loeffler** [comment]
No rush. I was just still playing with it but havent figure out yet a way to continue. I'll be patient.

**Comment by brcolow** [comment]
I am going out quite far on a limb here but I wonder if the `ICC_Profile` class can be used. Some documentation is found [here](http://docs.oracle.com/javase/7/docs/technotes/guides/2d/spec/j2d-color.html#wp62422) and also some examples from Github code search yield things such as https://github.com/enhorse/LFP-parser/blob/4b76dd4b1c1f12705a305b7f9eb94c4bad35a02d/src/main/java/xyz/enhorse/imageio/BasicICCProfile.java. The part of the TestFX code that would be worth trying this on is in AwtRobotAdapter.java `getCaptureRegion` method where we have an AWT `BufferedImage` that is then converting to an FX image via `SwingFXUtils`. Before we convert the image to a FX image I wonder if we can somehow change/modify the ICC color profile to "undo" what the macOS color profile is doing (i.e. go backwards to what's in the video memory as you propose). Not sure if any of that is possible - it will require quite a bit of investigation as to the AWT capabilities present in the JDK.

**Comment by JordanMartinez** [comment]
I use Linux, so I'm not sure if I can really help in this regard.

**Comment by Oliver-Loeffler** [comment]
Well, I'm just curious if Linux exposes the same behavior like macOS or like Windows.
It's also possible that either macOS or the JVM on macOS are behaving unexpectedly (or Windows).

**Comment by brcolow** [comment]
Using macOS 10.13 and the color profile "Color LCD"  I get the following shade files produced:

[OSName_ColorProfileNameHere_blueShades.txt](https://github.com/TestFX/TestFX/files/1377473/OSName_ColorProfileNameHere_blueShades.txt)
[OSName_ColorProfileNameHere_greenShades.txt](https://github.com/TestFX/TestFX/files/1377474/OSName_ColorProfileNameHere_greenShades.txt)
[OSName_ColorProfileNameHere_greyShades.txt](https://github.com/TestFX/TestFX/files/1377475/OSName_ColorProfileNameHere_greyShades.txt)
[OSName_ColorProfileNameHere_redShades.txt](https://github.com/TestFX/TestFX/files/1377476/OSName_ColorProfileNameHere_redShades.txt)

Note: I should have changed the name to LCDProfile instead of the default placeholder but was in a rush and just checked out your osx-colors branch on your fork. Hopefully you will be able to compare our results with your graphing wizardry :)

**Comment by brcolow** [comment]
@Oliver-Loeffler Hop in the [gitter chat](https://gitter.im/TestFX/TestFX) - I am working through the complexities involved in this issue - or at least doing some research.

**Comment by Oliver-Loeffler** [comment]
Hi, just have seen this, but yes, the colors are also shifted. On Windows there is no difference between expected and captured. I'll look into Gitter.

**Comment by Oliver-Loeffler** [comment]
Tonight or tomorrow I'll have graphs.

**Comment by JordanMartinez** [comment]
I have RedShift enabled by default, so before running these tests, I disabled it. I'm not sure if my color profile's name makes sense either. This is very unfamiliar territory.

[LinuxMint_LCDTV_blueShades.txt](https://github.com/TestFX/TestFX/files/1380106/LinuxMint_LCDTV_blueShades.txt)
[LinuxMint_LCDTV_greenShades.txt](https://github.com/TestFX/TestFX/files/1380107/LinuxMint_LCDTV_greenShades.txt)
[LinuxMint_LCDTV_greyShades.txt](https://github.com/TestFX/TestFX/files/1380108/LinuxMint_LCDTV_greyShades.txt)
[LinuxMint_LCDTV_redShades.txt](https://github.com/TestFX/TestFX/files/1380109/LinuxMint_LCDTV_redShades.txt)

**Comment by brcolow** [comment]
Note: https://lists.apple.com/archives/quartz-dev/2008/Feb/msg00079.html

We need to take the "naive" color that doesn't match (namely image.getPixelReader().getColor(0,0)) and then subtract some difference, dr, dg, db, and make an image with those colors and return that. The trick and difficult part is finding dr, dg, and db based on the color profile.

**Comment by brcolow** [comment]
Found this little nugget in JavaFX source code:

RT30650GUI.java:

```java
 public boolean testColor(Stage stage) {
    int x = (int)stage.getX();
    int y = (int)stage.getY();

    final int rgb[] = new int[1];
    runAndWait(() -> {
        Robot r = com.sun.glass.ui.Application.GetApplication().createRobot();
        rgb[0] = r.getPixelColor(x + SIZE/2, y + SIZE/2);
    });

    System.out.println("detected color: " + Integer.toHexString(rgb[0]));

    // On MacOSX the robot returns the color affected by the color profile.
    // And so the resulting color may differ from the requested one.
    // Here we have to check that the color is close to red rather than to green.
    return ((rgb[0] >> 16) & 0xff) > 200 && ((rgb[0] >> 8) & 0xff) < 100;
}
```

**Comment by brcolow** [comment]
Some Objective-C code from WebKit that changes color profiles (for the same reasons we want to):

https://github.com/WebKit/webkit/blob/master/Tools/DumpRenderTree/mac/LayoutTestHelper.m

I will try and do this color profile setting in the `GlassRobot.m` implementation for native-glass/mac as part of my work of moving Robot from the private to public API. This will not be able to be fixed before then unless we do something really drastic like introduce a JNI/JNA/ffi dependency to TestFX which I definitely want to stay away from.

**Comment by brcolow** [comment]
Changing the color profile as part of `GlassRobot.m` is almost certainly out of scope for the initial work of moving the Robot to the public API, but hopefully it will be a contribution I can make with the help of the new sandbox repository: https://github.com/javafxports/openjdk-jfx - but it will be a while.

**Comment by Oliver-Loeffler** [comment]
Not sure if this issue is of interest anymore. 
Given the progress on macOS, despite having tested this on newer versions, there is a chance that this is no longer a problem. Hence I am going to close this one.
