### ISSUE TITLE
Enhancement Request: Include OSGi headers in JAR Manifest

### ISSUE THREAD

**Issue by jtkb** [TestFX/TestFX#441]
I've been developing my own framework to allow JavaFX to take advantage of OSGi features ([here](https://github.com/jtkb/osgifx) and have been using TestFx to write some simple integration tests. Unfortunately the integration tests fail intermittently due to a class loading issue [described here](https://github.com/jtkb/osgifx/issues/1). These failures can be attributed to the TestFx jar file not being wrapped and resolved prior to the test commencing (some of the time).

One way to resolve this issue would be to include OSGi headers in the JAR manifest and introduce a 'dummy service'  that is registered once the TestFx bundle is activated. Test class could then request this service to be injected and hence would not execute until this dependency was available.

I have experimented by modifying TestFx to be built in such a way, [here](https://github.com/jtkb/TestFX/tree/feature/move_to_maven). (I had to move to Maven as I don't know Gradle and I find it too complicated for my needs).

The main change I have made is to the [testfx-core](https://github.com/jtkb/TestFX/tree/feature/move_to_maven/testfx-corel) where I have included a new sub-package ```org.testfx.osgi```. Also the [pom.xml](https://github.com/jtkb/TestFX/blob/feature/move_to_maven/testfx-core/pom.xmll) shows the maven bundle plugin settings I have used.

An example of a test using this change is [here](https://github.com/jtkb/osgifx/blob/bugfix/issue_1_testfx_failure/it/tests/src/test/java/com/javatechnics/osgifx/boot/TFxTest.java)

Is there any possibility such a change could be introduced into TestFx? There would be a build dependency on an OSGi framework bundle but wouldn't be needed otherwise except in an OSGi framework as no existed TestFX classes are modified to import OSGi packages.

**Comment by brcolow** [comment]
I would be open to merging a PR that adds such support - but it would need to use gradle as that's the build system TestFX uses.

**Comment by jtkb** [comment]
Sure thing. I think I need to modify the Gradle files in testfx-core, -internal-java8 and internal-java9 to build with the OSGi or bnd plugin so I will experiment with that. I also note issue #443 and I made a comment on there.
