### ISSUE TITLE
Mac KeyCode for the command button not working

### ISSUE THREAD

**Issue by LukeARohl** [TestFX/TestFX#452]
```
    @Test
    public void make_new_file_shortcut()
    {
    	press(KeyCode.COMMAND); //Command never gets pressed
    	push(KeyCode.COMMAND,KeyCode.N); //Only 'N' gets pressed
    	push(KeyCode.COMMAND); //Command never gets pushed
    	push(KeyCode.COMMAND,KeyCode.N); //Only 'N' gets pushed
    }
```

**Comment by brcolow** [comment]
What about:

```java
   @Test
    public void make_new_file_shortcut()
    {
    	press(KeyCode.SHORTCUT);
    	push(KeyCode.SHORTCUT,KeyCode.N);
    	push(KeyCode.SHORTCUT);
    	push(KeyCode.SHORTCUT,KeyCode.N);
    }
```

From Javadocs:

`The {@code shortcut} modifier is used to represent the modifier key which is
 used commonly in keyboard shortcuts on the host platform. This is for
 example {@code control} on Windows and {@code meta} (command key) on Mac`

**Comment by brcolow** [comment]
I am not able to reproduce a failure on macOS: https://github.com/brcolow/TestFX/commit/ab70971cbbec0293492fd18c1b9c746a7565b977

Tests pass on macOS headless java 8 and java 9:

https://travis-ci.org/TestFX/TestFX/jobs/300513706#L2585
https://travis-ci.org/TestFX/TestFX/jobs/300513707#L2620

**Comment by ChrisLMerrill** [comment]
FWIW, I am also experiencing this problem. TestFx 4.0.13, Java 10, Mac Mini (2011) High Sierra, Dell USB keyboard. I've tried KeyCode.COMMAND, CONTROL and WINDOWS keys and none allow me to _select all_ in a text field or a _multi-select_ in a list.

Any suggestions for how to debug this?
