### ISSUE TITLE
Runtime incompatibility: TestFx 4.0.9 compiled with Java 9

### ISSUE THREAD

**Issue by IreneAlvarezM** [TestFX/TestFX#466]
The version 4.0.9 has been compiled with Java 9 runtime, and since in my project i am using Java 8 runtime, it has stopped compiling, I am getting the error:
"org/testfx/api/FxRobot has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

Would it be possible to get the new jars with Java 8 compiled?

**Comment by brcolow** [comment]
Ah that is my mistake. I don't think I can fix it without issuing a new release.

**Comment by brcolow** [comment]
Let me know if 4.0.10-alpha works for you.

**Comment by IreneAlvarezM** [comment]
It works again with 4.0.10-alpha. Thank you!
