### ISSUE TITLE
Readme example doesn't work

### ISSUE THREAD

**Issue by jcornaz** [TestFX/TestFX#475]
Here is a sample test written following the example described on the [readme](https://github.com/TestFX/TestFX/blob/97a50a1d7ecc4e33d431400c34d3e0bd6553ffdd/README.md).

```java
public class TestFxTest extends ApplicationTest {

    @Override
    public void start(Stage stage) {
        Label label = new Label("Hello world");
        label.setId("greeting");

        Scene scene = new Scene(label);
        stage.setScene(scene);
        stage.show();
    }

    @Test
    public void shouldDisplayHelloWorld() {
        FxAssert.verifyThat("#greeting", LabeledMatchers.hasText("Hello world"));
    }
}
```

This fail with : 
```
java.lang.AssertionError: 
Expected: Labeled has text "Hello world"
     but: was null
```

Could you explain me why ?

**Comment by brcolow** [comment]
Can you post a full project (with build files, imports, etc.) that demonstrates this?

**Comment by jcornaz** [comment]
Here you are : https://github.com/jcornaz/testfx-test

The code in this project is an exact copy-past from here : https://github.com/TestFX/TestFX/wiki/Version-4:-Lifecycle, and it is failling as well.

**Comment by brcolow** [comment]
You must actually launch the application. Add:

```java
    @BeforeEach
    void setup() throws Exception {
        ApplicationTest.launch(ClickApplication.class);
    }
```

To `ClickApplicationTest.java`

**Comment by jcornaz** [comment]
Ok. Thank you for you.

Please add it to the readme as well.

Before closing this issue, could you tell me why is the purpose of overriding the `start` method if it is needed to launch the application (which will setup the stage too) ?

**Comment by jcornaz** [comment]
After testing your proposition, it doesn't fix the problem.

Now, I see the application launched, but the application is hanging, and the test are not blocked.

Note: I have update the example project, if you want to see it

**Comment by brcolow** [comment]
Here is a working project:

https://github.com/brcolow/testfx-test

I made some changes. I don't know which change exactly is the key as I am quite pressed for time. Perhaps you could investigate and let me know.

Thanks.

**Comment by jcornaz** [comment]
OK. I'll take a look.

Thank you.

**Comment by jcornaz** [comment]
Ok. I made a mistake in my last try, I used `Application` instead of `ApplicationTest` to launch my application before each test.

In your working project example, the change that makes the difference is adding the following in the test class :

```java
    @BeforeEach
    public void setup() throws Exception {
        ApplicationTest.launch(ClickApplication.class);
    }
```

Doing that makes useless to override the `start` method. You can update the test example of the [wiki](https://github.com/TestFX/TestFX/wiki/Getting-Started#simple-testfx-application-test)

for this working version :
```java
public class ClickApplicationTest extends ApplicationTest {

    @BeforeEach
    public void setup() throws Exception {
        ApplicationTest.launch(ClickApplication.class);
    }

    @Test
    public void should_contain_button() {
        // expect:
        verifyThat(".button", hasText("click me!"));
    }

    @Test public void should_click_on_button() {
        // when:
        clickOn(".button");

        // then:
        verifyThat(".button", hasText("clicked!"));
    }
}
```

You can update the readme too, with this :
```java
public class DesktopPaneTest extends ApplicationTest {

    @BeforeEach
    public void setup() throws Exception {
        ApplicationTest.launch(DesktopPane.class);
    }

    @Test
    public void should_drag_file_into_trashcan() {
        // given:
        rightClickOn("#desktop").moveTo("New").clickOn("Text Document");
        write("myTextfile.txt").push(ENTER);

        // when:
        drag(".file").dropTo("#trash-can");

        // then:
        verifyThat("#desktop", hasChildren(0, ".file"));
    }
}
```

**Comment by brcolow** [comment]
There are quite a few issues with the project you posted. Firstly you should be using the junit5 testfx dependency:

```
testCompile "org.testfx:testfx-junit5:4.0.10-alpha"
```

Secondly the ApplicationTest for Junit 5 should look like:

```java

@ExtendWith(ApplicationExtension.class)
public class ClickApplicationTest {

    @Start
    public void start(Stage stage) {
        Button button = new Button("click me!");
        button.setOnAction(actionEvent -> button.setText("clicked!"));
        StackPane sceneRoot = new StackPane(button);
        stage.setScene(new Scene(sceneRoot, 1000, 1000));
        stage.show();
        WaitForAsyncUtils.waitForFxEvents();
    }

    @Test
    public void should_contain_button() throws InterruptedException
    {
        // expect:
        verifyThat(".button", hasText("click me!"));
    }

    @Test public void should_click_on_button() {
        // when:
        clickOn(".button");
        WaitForAsyncUtils.waitForFxEvents();

        // then:
        verifyThat(".button", hasText("clicked!"));
    }
}
```

The README examples are for junit 4 and thus must have the junit 4 dependency. This will automatically call the ApplicationTest launch method.

**Comment by jcornaz** [comment]
ok, thank you for this usefull information.

I close this issue, as it solves my problem, and I now understand the reasons of it.

But, I still think, there is currentyl no clue in the readme, that the example wouldn't work with junit5, and there should be one.

Thank you very much for your help.

**Comment by jcornaz** [comment]
Besides, I think the following sentence:

> The following example application is written for JUnit 4 only. Here is an example of a test with testfx-junit5.

Should be moved from the end of the [module section](https://github.com/TestFX/TestFX/wiki/Getting-Started#modules) to the begining [code example](https://github.com/TestFX/TestFX/wiki/Getting-Started#simple-javafx-application) of the 'getting started guide'

Especially when reading technical documentation, I usualy don't expect the last sentence of the previous chapter to be so crutial for my understanding of the current chapter.

Thanks again.

**Comment by brcolow** [comment]
Feel free to edit the wiki with those changes :)

**Comment by jcornaz** [comment]
Ok. I didn't know I had the rights to edit the wiki ^^

It's done.
