### ISSUE TITLE
TableViewMatchers.containsRow method behaviour

### ISSUE THREAD

**Issue by MikhailMS** [TestFX/TestFX#499]
Hello there,

I've started to use your great library to test my small application and currently facing weird behaviour of the TableViewMatchers.containsRow method. As name applies, it should return true if TableView has entry which matches to the row, entered as Object... parameter.
For example, I'm expecting true when TableView contains 
```
row 1 -> "Blue", 1, false
row 2 -> "Red", 4, true
```
and I'm looking for row to have values -> "Blue", 1, false.
However method returns true, as it expects both row to be looked for and order is compulsory.
Is it how it should behave? Then the name is misleading :(

**Comment by brcolow** [comment]
Could you perhaps show a complete, self-contained test case? Thanks!

**Comment by MikhailMS** [comment]
Sure thing

This is the test case for my actual application (not the example from the initial message, but it's same idea)
    
 ```
   @Override
    public void start(Stage stage) {
        User client = new Client("t", "t");
        Basket userBasket = new Basket();

        Inventory inventory = new Inventory();
        try {
            inventory.addProducts(new Product("chicken", 1, 2.3),3);
            inventory.addProducts(new Product("apple", 0.151, 0.8), 2);
        } catch (InventoryException e) {
            e.printStackTrace();
        }

        client.setBasket(userBasket);

        stage.setScene(new Scene(InventoryScene.createInventoryTableView(inventory, client), 600, 400));
        stage.show();
    }

    @Test
    public void should_contain_data_in_rows_for_user() {
        verifyThat(".table-view", TableViewMatchers.containsRow("[apple, 0.151, 0.8, 2, false]"));
    }
```

Here I'm trying to test, if one of the rows in table view contains row with described values 
And, from `start` method, it's clear that row I'm looking for exists in table view.

However I'm getting following error 

```
java.lang.AssertionError: 
Expected: TableView has row: [[apple, 0.151, 0.8, 2, false]]
     but: was [[apple, 0.151, 0.8, 2, false], [chicken, 1.0, 2.3, 3, false]]
Expected :TableView has row: [[apple, 0.151, 0.8, 2, false]]
     
Actual   :[[apple, 0.151, 0.8, 2, false], [chicken, 1.0, 2.3, 3, false]]
```
So it seems like `TableViewMatchers.containsRow` method gets all cells and compares the cells I want against all cells from table view. Also, even if I pass both rows to this method as 
`TableViewMatchers.containsRow("[apple, 0.151, 0.8, 2, false], [chicken, 1.0, 2.3, 3, false]")`
it fails sometimes because order in which those rows appear in table view differs sometimes -> order in which I pass those parameters are important for the `TableViewMatchers.containsRow` method. So it seems like either error in the method itself or just name that misleading.

**Comment by brcolow** [comment]
The reason all the cells are being printed is because in order to know why the matcher fails one needs to indeed see every row (because the the `containsRow` method can match a row at any index).

Given that the table does indeed have the row, or at least they are being printed the same way is interesting.

My first guess/hunch is it is because of the floating point values not being exactly equal "under the hood", even though they are being printed the same way.

In order to verify this it would be nice to see exactly what is the Product class, are these floats? doubles? NumberProperty's?

**Comment by MikhailMS** [comment]
No, none of those are properties. Just raw doubles 
The reason for that is because I'm building GUI on top of the existing app and there were no need to change raw doubles and string to properties :) 

I doubt that 

> floating point values not being exactly equal "under the hood", even though they are being printed the same way
cause if I list both rows and order matches, than test passes but it doesn't happen always

**Comment by brcolow** [comment]
Is this example on Github or hosted anywhere else? I'd like to be able to see the TableView instantiation, the cell value factories, cell factories, etc.

**Comment by MikhailMS** [comment]
Absolutely
https://github.com/MikhailMS/java-shop-example/tree/gui-feature
TableView implementation is in InventoryScene file

**Comment by brcolow** [comment]
Ah, I think I see the problem. The way the API is intended to be used is like so:

```java
verifyThat(".table-view", TableViewMatchers.containsRow("apple", 0.151, 0.8, 2, false));
```

**Comment by MikhailMS** [comment]
Yep, that's worked :) thank you indeed for the help

**Comment by brcolow** [comment]
I will update the Javadocs to better explain the intended usage - sorry I didn't spot the problem sooner and asked for all the additional info.

**Comment by MikhailMS** [comment]
Not a problem at all :) issue is solved, that's more important. Thank you for your time - really appreciate it
