### ISSUE TITLE
NullPointerException on Empty cells

### ISSUE THREAD

**Issue by MikhailMS** [TestFX/TestFX#507]
Hello there,

I'm testing my table view with your library, and currently discovered an issue with empty cells.
So, if I got a scene with two table views, and one of the tables got one row of data with only one cell to have value and others are empty (which is desired), and I'm calling `TableViewMatchers.hasTableCell` to see, if this row has a cell with a value, I'm getting NullPointerException from `TableViewMatchers.getRowValues`, as it seems like this method doesn't handle empty cells(which seems to be a Null as a default value for TableView).

**Comment by brcolow** [comment]
Do you think you could make a simple example/test-case that demonstrates the current behavior versus expected behavior?

**Comment by torakiki** [comment]
I'm also getting the exception
```
java.lang.NullPointerException
	at org.testfx.matcher.control.TableViewMatchers.getRowValues(TableViewMatchers.java:195)
	at org.testfx.matcher.control.TableViewMatchers.containsRowAtIndex(TableViewMatchers.java:173)
	at org.testfx.matcher.control.TableViewMatchers.lambda$containsRowAtIndex$6(TableViewMatchers.java:126)
	at org.testfx.matcher.base.GeneralMatchers$3.matchesSafely(GeneralMatchers.java:124)
```
In my case it's something [like this](https://stackoverflow.com/questions/33353014/creating-a-row-index-column-in-javafx) so a table column with a cellFactory but no cellValueFactory... `getRowValues` throws a NPE here `column.getCellValueFactory().call(cellDataFeatures)`

**Comment by JanMosigItemis** [comment]
Hi, FYI I created a PR for this. Maybe it helps.
