### ISSUE TITLE
Combine Label-matching with CSS selectors

### ISSUE THREAD

**Issue by Philipp91** [TestFX/TestFX#51]
Very often, I need to click something that is ambiguous. I have stopped using CSS classes long ago, because something like `.button` is obviously not specific enough. Nesting them doesn't help much, either.
IDs are also a little difficult, because you would have to give each and every node an ID and ignore a warning for each ID that doesn't have a matching field on the controller. Also, IDs tend to be either lengthy (like "closeButtonInSettingsTab") or ambiguous ("closeButton").
That's mostly why I use labels for clicking stuff. Another advantage is that the tests become more readable.

But also with labels, I have the problem that they can be ambiguous. Just think of the "File" menu when two windows are open. This can of course be solved by something like `click(find("Target label", find("#moreSpecificLocation"))`. Due to some odd behavior of Java 8, I can't use `click(find(...))`, but have to write `click((Node) find(...))` instead. All that code gets pretty lengthy and unreadable.

Is there any good solution to this already? I want to do something like:
- Click a node labeled "Teachers", but I want the tab to be clicked and not the button and not the label, which happen to have the same label.
- Click a node that appears n times (e.g. once per table row or list row).
- Click a node in a different window.

One idea could be to extend CSS selectors. As far as I can see, there is nothing like type selectors in JavaFX (unlike `body` in web CSS). So every selectors starts with a `.` or a `#`. Hence, we could interpret selectors that do _not_ start with one of these characters as labels and allow something like this:
- `click("Teachers.tab")`
- `click("#myTabPane > Teachers")`
- `click(".button-area > Teachers")`

Also we could allow pseudo-classes that do not actually exist in JavaFX (just like jQuery interprets `:checked` and `:visible`) and allow something like:
- `#someTable :row(14) :cell(2)`
- `#someNode:parent`
- `:focused`
- ...

Downsides:
- Probably hard to implement.
- Might be confusing to users.
- Might be error-prone.

**Comment by zerat1983** [comment]
Can someone tell me is this issue still valid?
