### ISSUE TITLE
Pressing KeyCode for the Back Slash button not working

### ISSUE THREAD

**Issue by Amber-Moon** [TestFX/TestFX#515]
Hi,
I try to type a windows path using the following code:

  ```
private void writePath(String path) {
        char c;
        KeyCode code;
        for (int x = 0; x < path.length() - 1; x++) {
            c = paths.charAt(x);
            code = findKeyCode(c);
            press(code);
        }
    }
```
It run wells when pressing some characters like C, COLON ..
However, it returns " invalid key code" when trying to press a BACK_SLASH code.

Any idea please?

**Comment by brcolow** [comment]
Can you try using the FxRobot.write(..) method directly instead of iterating over the characters in the path?

**Comment by VipSaran** [comment]
@brcolow , which `write()` method do you mean?

**Comment by brcolow** [comment]
@VipSaran https://github.com/TestFX/TestFX/blob/master/subprojects/testfx-core/src/main/java/org/testfx/api/FxRobot.java#L505

**Comment by VipSaran** [comment]
Well, I guess that was introduced in v4, so was not aware. Thanks.

**Comment by brcolow** [comment]
@VipSaran No problem.
