### ISSUE TITLE
Changing defaultButton at runtime leads to test failures

### ISSUE THREAD

**Issue by jcornaz** [TestFX/TestFX#518]
Hello, 

I have tests failing, when I dynamically change the default button in the view.

## Example project
Project : https://github.com/jcornaz/testfx-travis-test/tree/4f4eac79e59b912ba8fab2c3906f5424c40ceb4a
Travis build : https://travis-ci.org/jcornaz/testfx-travis-test/builds/335532570

## Expected Behavior
1. Tests should pass, because :
  1.1. Manual testing succeed
  1.2. They pass if run one by one
2. Tests run with headless mode in Travis build should have the same result as if run locally.

## Actual Behavior
1. One test fail locally (one of the test which explicitly test if it is possible to trigger the action with the enter key)
2. Two tests fail in headless mode in Travis build (1 using enter key, 1 using click on the button)

## Specifications
  - Java 8
  - TestFx 4.0.11-alpha
  - Junit 5.1.0-M2
  - openjfx-monocle:8u76-b04

**Comment by brcolow** [comment]
Can you try adding a `WaitForAsyncUtils.waitForFxEvents();` after dynamically changing the Button and before asserting on its state?

**Comment by jcornaz** [comment]
I tried `WaitForAsyncUtils.waitForFxEvents()`, but it doesn't help.

And actually I'm never asserting the state of the button. I'm only asserting that the text of a label that should be changed by the button.

Here is my try with `WaitForAsyncUtils.waitForFxEvents()`:
commit: https://github.com/jcornaz/testfx-travis-test/commit/6a42621fef64b80065258fda81d4db612e069ce0
Travis build: https://travis-ci.org/jcornaz/testfx-travis-test/builds/337038763

**Comment by brcolow** [comment]
When running the tests locally, I get a failure with `testHelloWithEnter` where, after hitting enter, `#resultLabel` is empty.

**Comment by jcornaz** [comment]
Yes indeed that's the problem... the label shouldn't be empty...

**Comment by brcolow** [comment]
Oh, heh, it's because the key is never released, only pressed!

Using `verifyThat("#resultLabel", hasText("Hello Kotlin"), DebugUtils.informedErrorMessage(robot));`

You can see that:

```
      Keys pressed at test failure:
         ENTER
```

To press *and* release a key, you can use `type`, or manually call `press` then `release`.

**Comment by jcornaz** [comment]
Ahhh. Okay, indeed. Now it is clear. Thank you for the help.

**Comment by jcornaz** [comment]
Actually, I assumed that TestFx was recreating a new scene, robot, etc. for each test function. Which is apparently not the case. How could I achieve such isolation with TestFx ?
