### ISSUE TITLE
Test stage opening in button clicks

### ISSUE THREAD

**Issue by Timunas** [TestFX/TestFX#527]
Hello,

How is it possible to validate that when I click on a button that a new stage opened?
Is it possible in same test have:
- a main stage
- click on button in main stage that will open different stage
- validate things in different stage
- click to close diff stage
- back to main stage
- validate things
?

Best regards

**Comment by brcolow** [comment]
You should be able to use the `targetWindow(..)` methods in `FxRobot`. Take a look at https://github.com/TestFX/TestFX/blob/master/subprojects/testfx-core/src/test/java/org/testfx/service/finder/impl/WindowFinderImplTest.java

**Comment by Timunas** [comment]
Hi,
Thx for the reply. 
But will I need to setup all windows before test startup? Or will be possible to click the button than new window shows and I can play with it?

**Comment by brcolow** [comment]
There is no reason the windows need to all be created before the test runs.

**Comment by Timunas** [comment]
Thx!
