### ISSUE TITLE
Link to (Spock) Javadoc is broken on intro page

### ISSUE THREAD

**Issue by Mrodent** [TestFX/TestFX#531]
... I was trying to understand where the class ApplicationSpec which you use in your Spock example comes from... I hoped I might find this class by making my own Javadoc from the Gradle-downloaded .jars for spock-testfx... but surprisingly this doesn't appear to involve downloading the *sources.jar in question.

Though from the executable I was at least able to work out the class path for the import line...

And though... now I downloaded your source .zip from here... and I see that the Spock module is included.  Great.  But I'm new to Groovy and I don't know how to create a Javadoc from Groovy code... !

**Comment by JordanMartinez** [comment]
> But I'm new to Groovy and I don't know how to create a Javadoc from Groovy code... !

That sounds like an issue unrelated to this project.

And yes, the link to the javadoc for the spock package returns a [404](https://testfx.github.io/TestFX/docs/javadoc/testfx-spock/javadoc/index.html). Not sure why that is... I'm guessing an issue in the build?

**Comment by brcolow** [comment]
Ah yes, the link must be correct to: `http://testfx.github.io/TestFX/docs/javadoc/testfx-spock/groovydoc/index.html`, I will do that now.

**Comment by brcolow** [comment]
The link is now corrected on: http://testfx.github.io/TestFX/docs/javadoc/

**Comment by Mrodent** [comment]
Thanks
