### ISSUE TITLE
Test fails on linux with Monocle and Xvfb

### ISSUE THREAD

**Issue by BiosMono** [TestFX/TestFX#549]
## Expected Behavior
Tests resaults are same when running headless with Xvfb, or without it.

## Actual Behavior
Described test passes with Monocle on Linux, but fails after adding Xvfb.
Test scenerio -
Main app:

    public class MainApp extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        AnchorPane main = new AnchorPane();

       Scene scene = new Scene(main);

        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

    }

Actual test:

    public class TestFxBase extends ApplicationTest 
    {
        Stage stage1; 

       @Before
        public void setUpClass() throws Exception {
            ApplicationTest.launch(MainApp.class);
        }

      @After
      public void afterEachTest() throws TimeoutException {
          FxToolkit.hideStage();
          release(new KeyCode[]{});
          release(new MouseButton[]{});
      }

      @Override
      public void start(Stage stage) {
          stage.show();
      }

      @Test
      public void test() throws Exception {
        JFXPanel fxpanel = new JFXPanel();

        VBox vBox = new VBox();
        Platform.runLater(() -> {
            stage1 = new Stage();
            stage1.setScene(new Scene(vBox, 300, 250));
        });
        Thread.sleep(1000);

        Platform.runLater(stage1::show);
        Thread.sleep(1000);
        assertTrue(stage1.isFocused());   //fails with Xvfb
      }
    }

## Specifications

Version: 4.0.12-alpha
Platform: Linux

**Comment by brcolow** [comment]
And just to confirm you are running the test with headless properties? I.e. `-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500`?

**Comment by brcolow** [comment]
I am confused because it doesn't make any sense to run Monocle without xvfb. And if this issue is about the stage being focused in headless mode (i.e. with monocle and xvfb) then how is it different than #548

**Comment by BiosMono** [comment]
Thanks for reply and your advice. I´m using the properties as you mentioned, but after replacing `Thread.sleep(1000)` with `WaitForAsyncUtils.waitForFxEvents()` the test passes. I guess that 1000ms wasn´t enough on my virtual machine with low memory and a lot of other stuff running by the time, I was testing that. It still fails with Xvfb without Monocle, but since you´re saying, that thats incorrect usage, I think we can close this issue. 

I still feel like there are two options, "headfull" run with Xvfb, or headless run with Monocle and I don´t understand, why would I need to use them together, but any way to make it work is good for me. I guess we are not going to use Xvfb at all, when focus issue with Monocle going to be ok.

**Comment by brcolow** [comment]
I believe that xvfb is only used because we are running in headless mode (no display), and JavaFX requires monocle in order to run in headless mode. Using xvfb in headed mode (when you actually have a display) may make sense, but I am not sure what the use case would be. In theory it should work, as JavaFX should simply act as if it is using X11. All of the google results that I could find on "javafx xvfb" are related to headless testing, there is no mention of using xvfb with JavaFX in headed mode, so I am not sure myself.
