### ISSUE TITLE
Pause-Button

### ISSUE THREAD

**Issue by Philipp91** [TestFX/TestFX#55]
Another idea: Pretty often I would have loved to have a button like the "Pause"-button on the keyboard to press in order to pause the UI tests. This would be useful to cancel the tests (because you can't if the mouse moves all the time) and to interrupt them (because they run >10 minutes) in order to do someting like answer an e-mail, etc.

I don't know how this could be implemented. Maybe at the beginning of every TestFX method (or maybe only the important ones) call a method that does the following:
- Check if the pause key is pressed (somehow).
- If not, continue normally.
- If it is pressed, determine and save the currently active window.
- Show a modal dialog that says "The UI tests have been paused. Click to continue."
- Reactivate the previously active window.

So maybe you would have to press that button for a little while until the next call of the check method is reached, but that would be fine. Waiting 2-3 seconds is way better than either waiting 5 minutes or canceling and waiting the whole 10 minutes again later.

**Comment by brcolow** [comment]
Pretty cool idea, may revisit in the future.
