### ISSUE TITLE
Robot cursor movement speed cannot be changed

### ISSUE THREAD

**Issue by adamlb94** [TestFX/TestFX#573]
MAX_POINT_OFFSET_COUNT in MoveRobotImpl.java should be externally accessible. This value is used to interpolate cursor movement. Reducing the value of this from 200 (e.g. to 50) dramatically increases the movement speed of the mouse during tests.

A proposed solution is given below. This is based on the recent changes that made SLEEP_AFTER_CHARACTER_IN_MILLIS in WriteRobotImpl.java externally available.

    static {
        int maxOffsetCount;
        try {
            maxOffsetCount= Integer.getInteger("testfx.robot.move_max_count", 200);
        }
        catch (NumberFormatException e) {
            System.err.println("\"testfx.robot.move_max_count\" property must be a number but was: \"" +
                    System.getProperty("testfx.robot.move_max_count") + "\".\nUsing default of \"200\".");
            e.printStackTrace();
            offsetCount= 200;
        }
        MAX_POINT_OFFSET_COUNT = maxOffsetCount;
    }

**Comment by adamlb94** [comment]
No problem, I've just made a PR.

**Comment by brcolow** [comment]
Thanks very much. Merged.
