### ISSUE TITLE
Check text in MenuItem elements

### ISSUE THREAD

**Issue by Alexilmarranen** [TestFX/TestFX#577]
How can I check the text in MenuItem in the following configuration:
junit - 5.2.0, testfx - 4.0.13-alpha
In MainApp MenuBar contain Menu "File"(id:fileMenu), Menu "File" contain Menu "New"(id:newMenuItem).
I run this test:

```
@ExtendWith(ApplicationExtension.class)
class RootLayoutControllerTest {

    @Start
    void onStart(Stage stage) throws Exception {
        MainApp app = new MainApp();
        app.start(stage);
        stage.show();
    }

    @Test
    void menuBarHasTextInItems(FxRobot robot) {
        verifyThat("#fileMenu", org.testfx.matcher.control.LabeledMatchers.hasText("File")); //Success
        robot.clickOn("#fileMenu");//Success
        robot.moveTo("#newMenuItem", Motion.DEFAULT);//Success
        verifyThat("#newMenuItem", org.testfx.matcher.control.LabeledMatchers.hasText("New"));//Error
    }
}
```
and error: 

>java.lang.AssertionError: 
Expected: Labeled has text "New"
     but: was a com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer (<ContextMenuContent$MenuItemContainer[id=newMenuItem, styleClass=menu-item]>)
Expected :Labeled has text "New"

Any ideas how check this text?
Sorry if my question is dumb

**Comment by ribosradagast** [comment]
adding your code that sets up the button / menu and menu items would be very helpful

**Comment by Alexilmarranen** [comment]
I do not use programmatically set up of components - I load FXML file and init scene.
However, I wrote an identical example to my code with the same error.

```
   @Start
    void onStart(Stage stage) {
        MenuBar menuBar = new MenuBar();

        Menu menu = new Menu("File");
        menu.setId("fileMenu");

        MenuItem menuItem = new MenuItem("New");
        menuItem.setId("newMenuItem");
        menu.getItems().add(menuItem);

        menuBar.getMenus().add(menu);
        stage.setScene(new Scene(new StackPane(menuBar), 100, 100));
        stage.show();
    }

    @Test
    void menuBarHasTextInItems(FxRobot robot) {
        verifyThat("#fileMenu", hasText("File"));
        robot.clickOn("#fileMenu");
        robot.moveTo("#newMenuItem", Motion.DEFAULT);
        verifyThat("#newMenuItem", hasText("New"));//Error
    }
```

Retreat: Perhaps I do not understand the paradigm of using TestFX - why in all examples is used programmatically set up components? Is testing generally not meant to be a black box (the test methods should be separated from the working code, the test methods should call the real working code (for TestFX - the program or the scene of the real application, not the one that was programmed in the onStart method))? Testing a nearby code in the onStart method does not make sense. Or are they just examples?

**Comment by brcolow** [comment]
They are just examples. In real applications you should instantiate FXMLController's that contain all of the UI logic for your application.

**Comment by ribosradagast** [comment]
Came here to say just what brcolow edited his response to say.  Your node query is picking up the menu item container, not the labeled menu item itself.

If you wanted to just verify that a ui element has certain text, then I think it'd be smarter to just save a reference to the menu item and then do 
assertThat (menuItem.getText(), equals("New") 

and leave the robot out of it!

**Comment by Alexilmarranen** [comment]
@ribosradagast @brcolow 
It seems you are right about protected methods / elements. This should work, but it seems to me the more correct way would be to create a matcher for this class of elements. I'm not very experienced in programming, but I'll try to write this matcher. Many thanks for your help.

**Comment by Alexilmarranen** [comment]
I created the simplest matcher for MenuItemContainers. However, I'm not sure that I did everything right.
Are PRs welcome? If so, I probably need help (I never sent PR).

**Comment by brcolow** [comment]
PRs are very much welcome!

**Comment by brcolow** [comment]
Very good tutorials provided by GitHub [here](https://help.github.com/articles/creating-a-pull-request/).

**Comment by Alexilmarranen** [comment]
@brcolow thank you very much, I'll send PR soon

I would like to clarify the following:
I created a new MenuItemMatcher. When you use it, you get the following code:
````verifyThat(((ContextMenuContent.MenuItemContainer)robot.lookup("#newMenuItem").query()).getItem(), MenuItemMatchers.hasText("New"));````
Getting the ContextMenuContent.MenuItemContainer from lookup and cast for this type looks somewhat ugly. My question is why from lookup we get ContextMenuContent.MenuItemContainer? Does this make sense? Perhaps it makes sense to receive MenuItem directly? (I tried to implement this, but honestly did not even understand exactly how the lookup happens).

**Comment by brcolow** [comment]
It is really ugly and even uses a class from JavaFX's private API (namely ContextMenuContent). Setting the ID on the MenuItem and then looking it up would ideally return a MenuItem instance. TestFX relies on the [Node#lookup](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html#lookup-java.lang.String-) method for querying the scene graph for nodes. JavaFX is itself returning a ContextMenuContent.MenuItemContainer. It would be possible to add a "filter" that transforms this class into the MenuItem instance (if there is indeed a one-to-one correspondence between the two). I am not sure where such a filter would be most ideally added to the code base. I also don't know how many Nodes in JavaFX happen to behave in the following way: Given a Node A of type B, calling A.setId("someId") returns a Node of type C where B != C. It would be nice to identify such nodes are perhaps "correct" them so that the results of `lookup` are not counter-intuitive.

**Comment by Alexilmarranen** [comment]
I hope I did everything right.

I still feel that changing the tested class for testing purposes is a bad idea. I'll try to do a research
which classes behave in this way as MenuItem with lookup (class mismatch). At first glance this happens to all the elements called in the subwindow (Tooltip, MenuItem, ContextMenu, ...). This problem needs further investigation. Anyway, the idea with the filter seems to me good.
