### ISSUE TITLE
NodeQueryUtils.hasTextNode does not take "Text" shapes into account.

### ISSUE THREAD

**Issue by dg76** [TestFX/TestFX#599]
It checks only for "Labeled" and "TextInputControl" objects but not for "javafx.scene.text.Text" objects. Thus "lookup" does not find text that is in such a "Text" object.

**Comment by brcolow** [comment]
Correct. We have `TextMatchers` for that.

**Comment by dg76** [comment]
Ah, I see, thank you for this hint! Thank you very much for your quick reply! 😃

But doesn't that mean that I have to know for each text that is displayed on the screen if it is a "Text" or a "Label"? Wouldn't it be easier/better if I could just check for the existence of a text on the screen without knowing if it was displayed as a "Text" or a "Label"? 🤔
(I think often test cases are not written by the same people that wrote the code that is being tested.)

**Comment by brcolow** [comment]
Can you show me the test code you are using? Honestly I forget the purpose of `NodeQueryUtils.hasTextNode`, and maybe it does make sense to add a case for `javafx.scene.text.Text` classes, especially because they are `Node`s hierarchically.

**Comment by dg76** [comment]
I am probably not using the best functions. I have tried to check if a certain text appears on the screen. For this purpose I tried to use this:

`assertNotNull(lookup("The text that should appear.").queryParent())`

Internally this "lookup" uses NodeQueryUtils.hasNodeText . 

For my purpose I have now created a function lookupText (in Kotlin)

```
fun ApplicationTest.lookupText(text: String) =
    lookup(Predicate { (it as? Text)?.text == text 
                        || (it as? Labeled)?.text == text 
                        || (it as? TextInputControl)?.text == text})
```

and a function that checks if the text was found:

```
fun ApplicationTest.lookupTextIsFound(text: String): Boolean {
    val lookupText = lookupText(text)
    try {
        return lookupText.queryText() != null
    } catch (e: ClassCastException) {
        return lookupText.queryParent() != null
    }
}
```

There is probably a better way, I suppose? Thank you for your very quick responses! 😊

**Comment by brcolow** [comment]
I think that the if-statement in `NodeQueryUtils.hasTextNode` should be updated to check for `Text` instances. I will send a PR now. I think what you are doing is a valid way to test when you don't have the CSS id of the text, but only what text it contains.

**Comment by brcolow** [comment]
I will issue a new release within the next couple days. Thanks for your report.
