### ISSUE TITLE
Record UI elements for TestFX

### ISSUE THREAD

**Issue by plaidshirtakos** [TestFX/TestFX#605]
## Expected Behavior
There is an existing JavaFX based application, which I should write automated tests for. I just started to use TestFX(version 4.0.13-alpha) and looking for advice, how to record and identify UI objects of application. Are there some built-in solutions for this purpose?

## Actual Behavior
TestFX is unable to find elements of JavaFX application.
Button button = new Button("Submit");

## Specifications

  - Version: version 4.0.13-alpha
  - Platform: Windows 8.1

**Comment by brcolow** [comment]
Does the README not answer these questions? See, for example:

```java
        // then:
        assertThat(desktopPane).hasChildren(0, ".file");
        // or (lookup by css id):
        assertThat(lookup("#desktop").queryAs(DesktopPane.class)).hasChildren(0, ".file");
        // or (look up css class):
        assertThat(lookup(".desktop-pane").queryAs(DesktopPane.class)).hasChildren(0, ".file");
```

**Comment by brcolow** [comment]
I'm not sure what you mean by "record"?

**Comment by plaidshirtakos** [comment]
@brcolow  : How could I identify GUI elements from application? I am looking for some solution like xpath for Selenium WebDriver.

**Comment by brcolow** [comment]
Nodes in the scene graph can be looked up by their css id (which can be set using https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html#setId-java.lang.String-) or their css class (which is set for each Node in the scene-graph automatically by JavaFX). A Node's css class can be discovered by looking at https://gist.github.com/maxd/63691840fc372f22f470

**Comment by plaidshirtakos** [comment]
@brcolow  : I see, but I don't have access to application's source code. I need to write automated tests for this application.

**Comment by brcolow** [comment]
Ah, I see. TestFX is not really made for that, unfortunately.

**Comment by plaidshirtakos** [comment]
@brcolow : So, should I know internal structure of application to use TestFX?
Do you know any other tools to test JavaFX applications?

**Comment by psaikkonen** [comment]
[Scenic view](http://fxexperience.com/scenic-view/) can be used to inspect JavaFX applications for id and style class values.

Also, if you are familiar with Robot Framework, we have created a wrapper library for TestFX called [JavaFXLibrary](https://github.com/eficode/JavaFXLibrary).

**Comment by brcolow** [comment]
Closing as support for such a thing is currently out-of-scope. I would be very willing to accept contributions that add this functionality.
