### ISSUE TITLE
Clean Handling of HDPI

### ISSUE THREAD

**Issue by Ortner** [TestFX/TestFX#607]
## Issue
I'm currently migrating to Java 10 and some tests on mac are failing. One of them is the related to HDPI. At first, thanks @brcolow to implement and test the HDPI feature lastly, but the solution has one drawback: The GlassRobotTest fails on my system (that uses AWTRobot), as the wrong robot is detected. In the BoundsLocator routine.

I would propose a change in the architecture based on the following requirements/expectations

## Requirements
- The user of TestFx is generally expecting the coordinate space to be within JavaFx coordinates (regardless of the Monitor being HDPI or not).
- Common Interface for the RobotAdapter - In my Opinion, the RobotAdapter interface should be consistent, so all RobotAdapters should use the same coordinate space. (On first inspection, JavaFxRobot and AwtRobot are using  JavaFx coordinates and GlassRobot is using real screen coordinates in some cases)

## Proposal

Use JavaFx Coordinates down to the RobotAdapter. The RobotAdapter should handle the conversion depending on Java version and operating system.

Points that may be confusing about this:
- getBoundsOnScreen returns JavaFx coordinates

Advantages:
- general code is independent of used Adaptor

Disadvanges
- HDPI Screenshots wouldn't be possible (may be add a Raw option to the RobotsCaptureRegion?)

PR-Follows

**Comment by brcolow** [comment]
@Ortner Just wanted to report that HiDPI contract test has one failure on Windows with 200% DPI scaling (using AWT robot) on OpenJFX 11: https://ci.appveyor.com/project/testfx/testfx/build/master%201487/job/a9pnngw48kb9ksh3#L1051 - would you care to take a look and see if it's an easy fix? I ask because you are the most familiar with when/why scaling is needed. Thanks a lot.

**Comment by Ortner** [comment]
Gonna have a look at it when i‘m back from holydays...

**Comment by brcolow** [comment]
Sounds good. No rush whatsoever. Thanks.

**Comment by Ortner** [comment]
@brcolow Sorry, took a while.  
First: I kept the methods above, so the scaling methods are called in the right place in the logic of the other functions in case any configuration needs it in the future (it's quite easy to mess something up there).

Second: Is there still a problem? The test seems to pass in the current build. After a quick look into the code, the dimensions should be correct, if the capturePixelColor passes (which did in the referenced build).
