### ISSUE TITLE
stream().limit(-1) in MoveRobotImpl

### ISSUE THREAD

**Issue by Clashsoft** [TestFX/TestFX#618]
The following error is produced in some cases on our CI environment when trying to click on a button:

```
java.lang.IllegalArgumentException: -1
	at java.util.stream.ReferencePipeline.limit(ReferencePipeline.java:400)
	at org.testfx.robot.impl.MoveRobotImpl.moveMouseStepwiseBetween(MoveRobotImpl.java:124)
	at org.testfx.robot.impl.MoveRobotImpl.moveTo(MoveRobotImpl.java:63)
	at org.testfx.robot.impl.ClickRobotImpl.clickOn(ClickRobotImpl.java:57)
	at org.testfx.api.FxRobot.clickOn(FxRobot.java:595)
	at org.testfx.api.FxRobot.clickOn(FxRobot.java:643)
	at org.testfx.api.FxRobot.clickOn(FxRobot.java:60)
	at org.testfx.api.FxRobotInterface.clickOn(FxRobotInterface.java:641)
	at <our test class>:<the line where it calls clickOn("#someElement")
```

I am sorry to report that I have not found out the exact reason why and under what conditions this happens, but there does not seem to be any direct indicator of what is wrong due to the lack of a proper error message.

It seems like moveMouseStepwiseBetween calls the `limit` stream method with an argument `-1`, which is caused by the `path` list being empty. I have found that "should" not be possible, since it is filled by the `interpolatePointsBetween`, which should add exactly `totalStepsCount` points to that list, which is bounded to be >= 1. Perhaps the `limit` call can be avoided completely by using a simple indexed for loop in its place.

## Expected Behavior

A proper error message is produced, that shows what caused the mouse movement issue. E.g.: the node has a negative screen position, does not exist, etc.

## Actual Behavior

See above for stack trace.

## Specifications

  - Version: 4.0.13-alpha
  - Platform: macosx10.11
  - JUnit: 4.12
  - Gradle: 4.9

**Comment by brcolow** [comment]
Yes, I have also seen this. I will investigate - but not sure when I will have time. Might be a couple days.

**Comment by Clashsoft** [comment]
I added some lines explaining what I found during my investigation of the code - I hope it helps despite not having an example.

**Comment by brcolow** [comment]
Note the comment there: `// TODO(mike): Why is the limiting necessary?` - I don't understand why the limiting is necessary (logically it shouldn't do anything as the limit is set to the size of the list). But without it, IIRC, tests fail.

**Comment by brcolow** [comment]
Let's see what happens: https://github.com/TestFX/TestFX/pull/619

**Comment by Clashsoft** [comment]
I believe it causes the loop to skip the last element (which is why it's `size() - 1`). The last element is then moved to with `mouseRobot.move(targetPoint);`. I'm gonna guess it's there because of the waiting behaviour. But as this exception shows, it doesn't work when the path is empty. Can probably be fixed by using an indexed loop, and would be faster too.

**Comment by brcolow** [comment]
Ah, yes, that makes sense. For some reason I was thinking size() - 1 was the number of elements. Would you be interested in opening a PR?

**Comment by Clashsoft** [comment]
Yeah, sure!
