### ISSUE TITLE
While running .robot file from Robot framework IDE (RIDE) on ubuntu, the log says, "[ ERROR ] FxRobot not initialized, launch test application with the library". How can I get the FxRobot running?

### ISSUE THREAD

**Issue by prawinw** [TestFX/TestFX#623]
While running .robot file from Robot framework IDE (RIDE) on ubuntu, the log says, "[ ERROR ] FxRobot not initialized, launch test application with the library". How can I get the FxRobot running?

**Comment by brcolow** [comment]
Maybe take a look at https://github.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library. I am not familiar with the Robot framework.

**Comment by brcolow** [comment]
Closing for now as Robot framework support is out of the scope of TestFX support (at least for now, given that I do not use it and therefore cannot dedicate resources to supporting it. If you or anyone else is interested in contributing in that way we can re-open and discuss it further).
