### ISSUE TITLE
TestFX support for Java web start automation

### ISSUE THREAD

**Issue by manikandanks2000** [TestFX/TestFX#624]
##  Documentation not clear how to automate web start applications

Can you confirm whether its possible to automate java web start application using TestFX which runs on a seperate JVM thread.  

Any inputs will be appreciated

I have explored multiple tools  currenrtly and its not clear how to  gain access to the java start application running seperately

AssertJ
Jemmy
JFCUnit
Abbot

**Comment by brcolow** [comment]
I have no experience with Java webstart unfortunately. Sorry I can't be of any assistance in this matter.

**Comment by brcolow** [comment]
Also just want to make an additional note that JNLP/Java Web Start is being removed from Java 11 onwards so it is very difficult to dedicate any resources to making this happen. On the other hand I would be happy to review a pull-request that offers such functionality as long as it gracefully fails on Java 11+.
