### ISSUE TITLE
Robot class package changed to javafx.scene.robot in OpenJFX 11

### ISSUE THREAD

**Issue by mvsoder** [TestFX/TestFX#629]
Environment:
OpenJFX 11
OpenJDK 11
TestFX 4.0.14-alpha
Monocle jdk-11+23

It appears that the Robot class has moved from com.sun.glass.ui to javafx.scene.robot. Since TestFX is probably built against the pre-OpenJFX 11 API, this causes a ClassNotFoundException:

java.lang.NoClassDefFoundError: com/sun/glass/ui/Robot
	org.testfx.service.adapter.impl.GlassRobotAdapter.robotCreate(GlassRobotAdapter.java:53)
	org.testfx.service.adapter.impl.GlassRobotAdapter.useRobot(GlassRobotAdapter.java:158)
	org.testfx.service.adapter.impl.GlassRobotAdapter.lambda$getMouseLocation$4(GlassRobotAdapter.java:91)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	java.base/java.security.AccessController.doPrivileged(Native Method)
	com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
	com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	java.base/java.lang.Thread.run(Thread.java:834)
java.lang.ClassNotFoundException: com.sun.glass.ui.Robot
	java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	org.testfx.service.adapter.impl.GlassRobotAdapter.robotCreate(GlassRobotAdapter.java:53)
	org.testfx.service.adapter.impl.GlassRobotAdapter.useRobot(GlassRobotAdapter.java:158)
	org.testfx.service.adapter.impl.GlassRobotAdapter.lambda$getMouseLocation$4(GlassRobotAdapter.java:91)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	java.base/java.security.AccessController.doPrivileged(Native Method)
	com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
	com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	java.base/java.lang.Thread.run(Thread.java:834)
--- Trace of caller of unhandled exception in Async Thread ---
	java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
	org.testfx.util.WaitForAsyncUtils$ASyncFXCallable.<init>(WaitForAsyncUtils.java:650)
	org.testfx.util.WaitForAsyncUtils.asyncFx(WaitForAsyncUtils.java:258)
	org.testfx.util.WaitForAsyncUtils.waitForAsyncFx(WaitForAsyncUtils.java:443)
	org.testfx.service.adapter.impl.GlassRobotAdapter.getMouseLocation(GlassRobotAdapter.java:90)
	org.testfx.robot.impl.BaseRobotImpl.retrieveMouse(BaseRobotImpl.java:82)
	org.testfx.robot.impl.MoveRobotImpl.moveTo(MoveRobotImpl.java:67)
	org.testfx.robot.impl.ClickRobotImpl.clickOn(ClickRobotImpl.java:55)
	org.testfx.api.FxRobot.clickOn(FxRobot.java:582)
	org.testfx.api.FxRobot.clickOn(FxRobot.java:630)
	org.testfx.api.FxRobot.clickOn(FxRobot.java:59)
	org.testfx.api.FxRobotInterface.clickOn(FxRobotInterface.java:639)
	com.xeomar.xenon.tool.about.AboutToolOpenTest.execute(AboutToolOpenTest.java:18)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:566)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by brcolow** [comment]
You are indeed correct. With the very patient help of @kevinrushforth, we made that change to upstream OpenJFX: https://github.com/javafxports/openjdk-jfx/pull/36. Also we have already made the changes necessary to support Java 11: https://github.com/TestFX/TestFX/pull/606. All that's necessary is to make a new release, which I will finish up shortly (within 2-3 days max).

**Comment by brcolow** [comment]
Version [4.0.15-alpha](https://github.com/TestFX/TestFX/releases/tag/v4.0.15-alpha) was released today. It should be synced with Maven Central in 24 hours. This is the first time I will be attempting to use the [deploy script](https://github.com/TestFX/TestFX/blob/master/.ci/deploy.sh) to sync with Maven Central instead of the Bintray web UI so it may not work. If that's the case I will have to manually sync tomorrow and it may take an additional 24 hours. I'd like to wait before manually syncing so that I know if the deploy script is working or not 😄.

**Comment by brcolow** [comment]
Version 4.0.15-alpha has been synced to [Maven Central](http://central.maven.org/maven2/org/testfx/testfx-core/4.0.15-alpha/).

**Comment by mvsoder** [comment]
Fantastic work! All 289 of my tests are passing with 4.0.15-alpha.

**Comment by mvsoder** [comment]
My compliments to @brcolow and @kevinrushforth for the excellent work. I'm loving Java 11 and JavaFX 11.

**Comment by brcolow** [comment]
@mvsoder That's great to hear. Thanks for your kind words.
