### ISSUE TITLE
(testfx-junit5) ApplicationExtension.afterEach does not clean Mouse/Key events

### ISSUE THREAD

**Issue by arnobl** [TestFX/TestFX#632]
## Expected Behavior

Using `ApplicationTest` provided by `testfx-junit`, the `internalAfter` method cleans the remaining events:
```java
    @AfterEach
    public final void internalAfter() throws Exception {
        // release all keys
        release(new KeyCode[0]);
        // release all mouse buttons
        release(new MouseButton[0]);
        FxToolkit.cleanupStages();
        FxToolkit.cleanupApplication(new ApplicationAdapter(this));
    }
```

## Actual Behavior

Using  `ApplicationExtension` provided by `testfx-junit5`, the `afterEach` method does not clean the remaining events:
```java
    @Override
    public void afterEach(ExtensionContext context) throws Exception {
        FxToolkit.cleanupApplication(new ApplicationAdapter(applicationFixture));
    }
```
To make it works as before I have to add in my test class:
```java
	@AfterEach
	void afterEach(final FxRobot robot) {
		robot.release(new KeyCode[0]);
		robot.release(new MouseButton[0]);
		WaitForAsyncUtils.waitForFxEvents(); // required to wait for the end of the UI events processing
	}
```
I guess these lines should be added at the beginning of `ApplicationExtension.afterEach`.

## Specifications

  - Version: 4.0.15-alpha
  - Platform: linux

**Comment by brcolow** [comment]
@arnobl Would you have time to open a PR? If not I will do so, but you deserve the contribution 👍.

**Comment by arnobl** [comment]
I will do that soon.

**Comment by brcolow** [comment]
Fixed by https://github.com/TestFX/TestFX/pull/633.
