### ISSUE TITLE
Running TestFX with Cucumber

### ISSUE THREAD

**Issue by Jeredriq** [TestFX/TestFX#635]
## Expected Behavior

Running TestFX with Cucumber.

## Actual Behavior

TestFX doesnt create a new instance for Cucumber tests and therefore could not find any nodes. Even though my base class perfectly works with only testfx tests.

[For more details, please check stackoverflow question here](https://stackoverflow.com/questions/52853515/using-testfx-with-cucumber)

Seems like testfxbase doesnt start the application therefore couldnt find any nodes. Is there a way to achieve this?

**Comment by brcolow** [comment]
In order for this to work I believe we will need to implement a sub-project that supports the Cucumber test framework like we have for Junit 4, Junit 5, and Spock. I would be very happy to accept a PR that adds such a subproject.

**Comment by brcolow** [comment]
I noticed that in the Stackoverflow question you have both legacy and new TestFX dependencies:

```
<dependency>
    <groupId>org.loadui</groupId>
    <artifactId>testFx</artifactId>
    <version>3.1.2</version>
</dependency>
<dependency>
    <groupId>org.testfx</groupId>
    <artifactId>testfx-core</artifactId>
    <version>4.0.6-alpha</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.testfx</groupId>
    <artifactId>testfx-junit</artifactId>
    <version>4.0.6-alpha</version>
</dependency>
```

To start with (it won't fix your issue, however) you should remove the old `org.loadui.testfx` dependency and bump TestFX version from `4.0.6-alpha` to `4.0.14-alpha`.

**Comment by brcolow** [comment]
To assert that a node exists you could do either:

Hamcrest:

```java
import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.not;
import static org.testfx.api.FxAssert.verifyThat;

// ...
verifyThat(fxRobot.lookup("#someNode").tryQuery(), is(not(equalTo(Optional.empty()))));
```

AssertJ

```java
import static org.testfx.assertions.api.Assertions.assertThat;

//...

assertThat(lookup("#someNode").tryQuery()).isNotEmpty();
```

I am not sure why the application is not starting, I would need to see a full code example.

**Comment by brcolow** [comment]
Can you please try with the latest version of testfx-core and testfx-junit? Furthermore, do you get any exceptions? Sorry for the generic suggestions.

Also this is not the right monocle dependency:

```xml
<dependency>
  <groupId>org.jfxtras</groupId>
  <artifactId>openjfx-monocle</artifactId>
  <version>1.8.0_20</version>
</dependency>
```

However, you are not testing in headless mode so that should not matter.

I have no experience using Cucumber, and I am not sure if any extra infrastructure needs to be added to TestFX to support your use-case. I am unclear if Cucumber is just a JUnit addon or it's own library. This is unsupported territory in terms of TestFX's scope of support.

**Comment by Jeredriq** [comment]
I've changed to headless mode for testing it, to see it open an application as usual in headless. But it didnt. I just get this
`org.loadui.testfx.exceptions.NoNodesFoundException: No nodes matched 'TextInputControl has text "Can you find this label"'.`
Cucumber is its own library. 


On the method below, there's no @Test tag maybe that causes the problem. Is there a way for me to start application even though there's no @Test tag? 

```
@Given("^That \"([^\"]*)\" Exists$")
    public void thatExists(String arg0) {
        String labelText = "Can you find this label text";
        clickOn(labelText);
        sleep(1000);
        verifyThat(lookup("#someNode").tryQuery(), is(not(equalTo(Optional.empty()))));
        verifyThat("#labelId",(Label label)-> {
            String text = label.getText();
            return text.contains(labelText);
        });
    }
```

**Comment by brcolow** [comment]
I am confused how you could get an old exception from TestFX 3.x "org.loadui.testfx.exceptions.NoNodesFoundException" when you are using TestFX 4.x which should be "org.testfx.service.query.EmptyNodeQueryException".

**Comment by Jeredriq** [comment]
First of all, I'm terribly sorry for the late response.


I upgraded as you said and now it says

```

org.testfx.api.FxRobotException: the query "Can you find this label text" returned no nodes.
    at org.testfx.api.FxRobot.queryVisibleNode(FxRobot.java:949)
    at org.testfx.api.FxRobot.pointOfVisibleNode(FxRobot.java:922)
    at org.testfx.api.FxRobot.clickOn(FxRobot.java:630)
    at org.testfx.api.FxRobot.clickOn(FxRobot.java:59)
    at org.testfx.api.FxRobotInterface.clickOn(FXRobotInterface.java:639) 
    at MyStepdefs.thatExists(MyStepdefs.java:21)
    at *.That "Can you find this label" Exists(Labels.feature:6)
```

MyStepDefs.java 20 and 21 is as it follows:

```
String labelText = "Can you find this label text";
clickOn(labelText);
```

this works great without cucumber ofc. And running it headless/headfull doesnt change anything because even though its headfull application does not start.

 And you can find the code in here:
https://github.com/Jeredriq/CucumberWithTestFX

I just updated dependencies as you said

**Comment by trzimar** [comment]
It works, but you have to move 
`ApplicationTest.launch(Main.class);`
in `MyRunner` class to static BeforeClass method `setupHeadlessMode()`

**Comment by Jeredriq** [comment]
@trzimar Thanks my dude but for some reason I cant run it in headless mode now, do you have any idea why it can be?


```
@RunWith(Cucumber.class)
@CucumberOptions(plugin = { "pretty" })
public class MyRunner extends ApplicationTest{

 @BeforeClass
    public static void setupHeadlessMode() {
            ApplicationTest.launch(Main.class);
            System.setProperty("testfx.robot", "glass");
            System.setProperty("testfx.headless", "true");
            System.setProperty("prism.order", "sw");
            System.setProperty("prism.text", "t2k");
            System.setProperty("java.awt.headless", "true");

   }

```

**Comment by trzimar** [comment]
@Jeredriq you need to set properties first and **then** call `ApplicationTest.launch(Main.class);`

**Comment by Jeredriq** [comment]
Sometimes my brain just dies. ¯\\_(ツ)_/¯

Thanks!

**Comment by klok0693** [comment]
As @ThijsVries noted, start new app instance for scenario is a problem. After spending several days, trying to fix it, we had found fast solution, using containerization via Docker and re-ran image for every test. Maybe it would be helpful for someone
