### ISSUE TITLE
"JUnit 5 with AssertJ Assertions" example from README possibly not working

### ISSUE THREAD

**Issue by JanMosigItemis** [TestFX/TestFX#647]
Hello there,

did I get it wrong, or is the `JUnit 5 with AssertJ Assertions` example in the README.md slightly wrong?
It says
```java
@Test
    void should_contain_button() {
        assertThat(button).hasText("click me!");
        assertThat(lookup("#myButton").queryAs(Button.class)).hasText("click me!");
        assertThat(lookup(".button").queryAs(Button.class)).hasText("click me!");
        assertThat(lookup(".button").queryButton()).hasText("click me!");
    }
```

But imo the lookup calls are missing a class identifier, because the test does not inherit from ApplicationTest anymore:

```java
@Test
    void should_contain_button(FxRobot robot) {
        assertThat(button).hasText("click me!");
        assertThat(robot.lookup("#myButton").queryAs(Button.class)).hasText("click me!");
        assertThat(robot.lookup(".button").queryAs(Button.class)).hasText("click me!");
        assertThat(robot.lookup(".button").queryButton()).hasText("click me!");
    }
```

**Comment by brcolow** [comment]
Thanks for pointing that out. I believe ideally that the test class should `extends FxRobot` so that the code looks a bit cleaner. I think we should add the missing `extends FxRobot` to the README example, unless there is a reason it should not be added I am not aware of?

**Comment by JanMosigItemis** [comment]
Well unless it really is required, I'd say extending the test class is a nono, because this would prevent the implementors from letting the class extend their own, probably more important, test super classes. Imo the option to inject FxRobot into the method is just fine.

**Comment by brcolow** [comment]
But couldn't their super-class extend FxRobot?

**Comment by JanMosigItemis** [comment]
Sure it could. However, some people prefer to not inherit from the testing framework itself in order to keep test code robust against changes in used frameworks.

Anyway, since this is just an example, the focus should be: Make it work. In order for this to be accomplished, just putting an `extends FxRobot` or using the method injection is sufficient imo.

**Comment by jasons2000** [comment]
can you show a quick example of the injection method.

**Comment by JanMosigItemis** [comment]
How about this?

```java
import static org.testfx.assertions.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.runner.RunWith;
import org.testfx.api.FxRobot;
import org.testfx.framework.junit5.ApplicationExtension;
import org.testfx.framework.junit5.Start;

import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

@ExtendWith(ApplicationExtension.class)
@RunWith(JUnitPlatform.class)
public class AppUiTest {

    private Button button;

    @Start
    void onStart(Stage stage) {
        button = new Button("click me!");
        button.setId("myButton");
        button.setOnAction(actionEvent -> button.setText("clicked!"));
        stage.setScene(new Scene(new StackPane(button), 100, 100));
        stage.show();
    }

    @Test
    void buttonTest(FxRobot robot) {
        assertThat(button).hasText("click me!");
        assertThat(robot.lookup("#myButton").queryAs(Button.class)).hasText("click me!");
        assertThat(robot.lookup(".button").queryAs(Button.class)).hasText("click me!");
        assertThat(robot.lookup(".button").queryButton()).hasText("click me!");
        robot.clickOn(button);
        assertThat(robot.lookup(".button").queryButton()).hasText("clicked!");
    }
}
```

The instance of `FxRobot` is "injected" into the test method `buttonTest`.

**Comment by brcolow** [comment]
Would you be interested in submitting a PR to correct the README?

**Comment by JanMosigItemis** [comment]
Sure, stay tuned.

**Comment by JanMosigItemis** [comment]
@brcolow PR is ready: https://github.com/TestFX/TestFX/pull/649
