### ISSUE TITLE
TableViewMatchers.hasTableCell: fails if cell is not visible in viewport

### ISSUE THREAD

**Issue by kleopatra** [TestFX/TestFX#651]
Having a table with many rows, such the last is off the viewport, hasTableCell(contentOfLast) fails. Which is not really surprising: the cell doesn't exist. 

The (minor) problem is the api doc: it might be improved to emphasize that the method matches "visible" cells and what client code can do to guarantee that the tested cell is showing in the viewport. Nit-pick: a cell has no "value", it has a textProperty and (afaict) the method is matching against that textProperty :) 

Something like:

    /**
     * Creates a matcher that matches all {@link TableView}s that has a visible {@link javafx.scene.control.TableCell}
     * whose textProperty or {@code value.toString()} equals the given value.
     * <p>
     * Test code must ensure that the cell is visible by scrolling it into the viewport before using
     * the matcher:
     *  <pre><code>
     *       int row = ...
     *       int col = ...
     *       tableView.scrollTo(row);
     *       tableView.scrollToColumn(col);
     *       verifyThat(tableView, hasTableCell(contentOfCell);
     * </code></pre>
     */

**Comment by brcolow** [comment]
If you change it to:

```java
/**
 * Creates a matcher that matches all {@link TableView}s that have visible {@link javafx.scene.control.TableCell}s
 * with a {@code textProperty} or {@code value.toString()} that equals the given value.
 * <p>
 * Test code must ensure that the cell is visible by scrolling it into the viewport before using
 * the matcher:
 *  <pre><code>
 *       int row = ...
 *       int col = ...
 *       tableView.scrollTo(row);
 *       tableView.scrollToColumn(col);
 *       verifyThat(tableView, hasTableCell(contentOfCell);
 * </code></pre>
 */
```

(just minor grammar corrections) and submit a PR I'll happily merge it :)

**Comment by kleopatra** [comment]
Thanks for the grammar improvements :) 

Actually, the code snippet is not quite correct in 

1. not wrapping the change in runLater and wait and
1. wrong method name for column scrolling (*cough) 

while moving the scroll onto the fx-app thread is not always needed (as long as no new rows/cells need to be created nor any child nodes of them would be removed/added), I think that it's a good habit ..

So finally the snippet should be:

````
 *  <pre><code>
 *       int row = ...
 *       int col = ...
 *       Platform.runLater(() -> {
 *           tableView.scrollTo(row);
 *           tableView.scrollToColumnIndex(col);
 *       });
 *       WaitForAsyncUtils.waitForFxEvents();
 *       verifyThat(tableView, hasTableCell(contentOfCell);
 * </code></pre>
````
btw, couldn't setup my Eclipse quickly for a pull request, so it has to wait until I have more time - please feel free to just c&p :)
