### ISSUE TITLE
TestFX with Spock & Openjdk11 -  Zero test results

### ISSUE THREAD

**Issue by dvdfmiller** [TestFX/TestFX#656]
## Expected Behavior
My TestFX/Spock test to be executed

## Actual Behavior
My TestFX/Spock test is not executed and I get zero test results.

I have documented the problem here:
https://stackoverflow.com/questions/55894842/testfx-spock-gradle-project-openjdk-11-zero-test-results

## Specifications

**Gradle build dependencies:**
        implementation 'org.testfx:testfx-spock:4.0.15-alpha'
	testCompile    'org.testfx:testfx-core:4.0.15-alpha'		
	testCompile (group: 'org.spockframework', name: 'spock-core', version: '1.3-groovy-2.5')
	testCompile ('org.codehaus.groovy:groovy-all:2.5.6')
	testRuntime(
		'com.athaydes:spock-reports:1.2.7',
		'cglib:cglib-nodep:3.2.4')

Openjdk: version = "11.0.2"
Gradle: 5.0
Eclipse: Version: 2019-03 (4.11.0)

**Comment by brcolow** [comment]
Interesting. I will try and look into this. Currently we only build `testfx-spock` on Java 8 for historical Groovy compatibility reasons. So I doubt anyone has ever tried to use `testfx-spock` on Java 11 but it certainly should be possible now.

**Comment by dvdfmiller** [comment]
Understood & thanks. I wonder whether testfx-spock has/needs Automatic-Module-Name defined in the JAR's manifest. I couldn't see this in the sources JAR (testfx-spock-4.0.15-alpha-sources.jar). 

Let me know if you need anything from me to help.
best regards
David

**Comment by dvdfmiller** [comment]
I noticed that testfx.junit has this in the manifest:
Automatic-Module-Name: org.testfx.junit

And I checked that testfx-spock-4.0.15-alpha.jar doesn't have an Automatic-Module-Name. Shouldn't this be "org.testfx.spock"?

I also wondered whether I needed to do this in my build.gradle:

`	testCompile('org.testfx:testfx-core:4.0.15-alpha') {
	exclude group: 'org.testfx', module: 'testfx-internal-java8'
	}	
`
`testCompile ('org.testfx:testfx-internal-java9:4.0.12-alpha')`

but it didn't solve the problem.

**Comment by brcolow** [comment]
Do you have a link to any info about using Groovy with jigasw modules? I found https://stackoverflow.com/questions/50163197/groovy-java-9-modules-support and https://stackoverflow.com/questions/50661000/groovy-3-on-java-10-module-info for example. Leaves many questions to be answered. For example:

1.) Should we update the version of groovy to 3.x?

2.) Is it appropriate to have a `module-info.java` file when we are using the groovy gradle plugin to compile `testfx-spock`?

The `testfx-spock` sub-project was contributed by @JordanMartinez (and thanks to him for doing so) but to be honest I know almost nothing about Groovy let alone maintaining a Groovy library used by others! Therefore in order to fix this issue I will really need someone knowledgeable to step in and guide the way.

**Comment by dvdfmiller** [comment]
Please see JDK11 section towards the bottom of this page:
http://groovy-lang.org/releasenotes/groovy-2.5.html
This page also has a link to a sample build.gradle:
https://github.com/apache/groovy/blob/master/subprojects/groovy-jaxb/build.gradle

Answering your questions:
1) Looks like from the link above that groovy 2.5 provided support for modular java and that groovy 3 solves the split package problem, and so it would seem that upgrading to groovy 3 isn't necessary if split packages are not involved.
2) I would have thought that if you are compiling with JDK11 then you would need a module-info.java even if it's minimal eg
`module org.testfx.spock{exports org.testfx.spock;}`
assuming there is a module and a package called org.testfx.spock.

Unfortunately I am not speaking knowledgeably about Groovy (which I don't know at all) and unable to guide the way. And so I am afraid that my answers are just guesses! :)

**Comment by JordanMartinez** [comment]
Hey all. Just FYI. I've moved on to PureScript, so I won't be responding to any of the messages here anymore. I don't know how much I'd be able to help anyways, since it's been quite some time since I touched Groovy.

**Comment by dvdfmiller** [comment]
I have found that plugin:
`'org.openjfx.javafxplugin' version '0.0.7'`
interferes with the execution of spock on Openjdk 11.

In a gradle spock-only project without this plugin Spock tests work, and with this plugin I get the zero tests results that I reported! This leads me to think that the plugin is causing the problem.

Trying now to run a gradle TestFX with Spock project with this plugin removed though I am meeting some other groovy problems. Will report back on progress.

**Comment by dvdfmiller** [comment]
I have found a solution and **Testfx with Spock** does in fact work with Openjdk 11.

I removed the plugin:
     `'org.openjfx.javafxplugin' version '0.0.7'`
and reworked my gradle.build.

I have posted the solution here:
https://stackoverflow.com/questions/55894842/testfx-spock-gradle-project-openjdk-11-zero-test-results/56012467#56012467

Many thanks for your help.
best regards
David
