### ISSUE TITLE
Module org.testfx should not contain package org.assertj.core.error.future

### ISSUE THREAD

**Issue by koppor** [TestFX/TestFX#682]
## Expected Behavior

No module issues during compilation.

## Actual Behavior

I get following output:

    Module org.testfx contains package org.assertj.core.error.future,
    module org.assertj.core exports package org.assertj.core.error.future to org.testfx

Refs https://github.com/JabRef/jabref/pull/3421/#issuecomment-524613616 --> https://travis-ci.org/JabRef/jabref/jobs/576385529

I will try to create an MWE. I hope, however, that someone has an idea for that.

## Specifications

  - Version: `org.testfx:testfx-core:4.0.+ -> 4.0.17-alpha-SNAPSHOT`, `org.testfx:testfx-junit5:4.0.+ -> 4.0.17-alpha-SNAPSHOT`
  - Platform: `openjdk version "11.0.2" 2019-01-15`

```
javafx {
    version = "11.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.web', 'javafx.swing' ]
}
```

**Comment by koppor** [comment]
Downgrade to 4.0.15 helped to solve this issue.

**Comment by brcolow** [comment]
Can you test with the latest SNAPSHOT?

**Comment by koppor** [comment]
I tried, but now I am having trouble with hamcrest :-/. See https://github.com/JabRef/jabref/pull/5397. Could not dive into it more.

**Comment by koppor** [comment]
Will create another issue if I find out more. The current gut feeling is that is an issue with hamcrest
