### ISSUE TITLE
proposal: new '@TestFx annotation and corresponding [Selective]JavaFxInterceptor extension to control thread execution.

### ISSUE THREAD

**Issue by RalphSteinhagen** [TestFX/TestFX#700]
First, thanks a lot for this lib and making JavaFX more unit-testable!

This concerns whether `@Test`  functions are executed within our outside the JavaFX UI thread.

We wrote some small JUnit 5-compatible extensions that can -- in addition to the robot interface -- control whether the individual unit tests are executed within the JavaFX UI thread (ie. simple getter/setter consistency tests) or by one of the JUnit thread pool tasks. Usage example:
a) `@ExtendWith(JavaFxInterceptor.class)` before the test class:
 - functions annotated with `@TestFx` and/or `@Test` are executed within the JavaFX UI thread

b) `@ExtendWith(SelectiveJavaFxInterceptor.class)` before the test class:
 - only test functions annotated with `@TestFx` are executed within the JavaFX UI thread
 - functions with `@Test` are executed by JUnit's standard thread pool

Implementation and examples can be found at (Apache 2.0, no re-use restrictions):
https://github.com/GSI-CS-CO/chart-fx/tree/master/chartfx-chart/src/test/java/de/gsi/chart/ui/utils

We thought this might be also useful for other TestFX users. I hope that the new functionality makes the testing of JavaFX classes and the readability of the corresponding unit-tests more consistent for the different use cases.

Enjoy!

**Comment by brcolow** [comment]
Would you be willing to submit a PR so we can add this to testfx-junit5?

**Comment by RalphSteinhagen** [comment]
@brcolow am feeling a bit shy, also because I wouldn't have much else to contribute right now. 

For me some of the open design questions are:
* is having a utility class OK for TestFX?
* should this possibly be part of the 'ApplicationExtension'?
* is the `@TestFx` annotation OK with your design goals?
* is the configurable distinction between `@TestFx` and `@Test` using the two different extensions necessary or would just `@Test` always being executed in the JavaFX UI thread suffice.

The thing is that these design choices open your interface to many more possibilities. While I am personally happy to and prefer to provide such rich and diverse interface for our users within our projects, I also know that some other developers prefer to have a very limited scope of functionalities they'd like to provide to ease their long-term maintenance goals (ie. less code, less to maintain). Thus I feel it be better that the TestFX core developer take the decision whether this fits (as is) or needs to be modified to whatever target is preferred.

In any case, you are free to re-use whatever piece of the code and unit-tests you like and find useful.

P.S. we found another sort-of bottleneck of TestFX in cases one has a project with many UI related different unit-tests (e.g. one unit-test file per UI class): the initialisation of the Stage prior to `@Start` can take quite some time lengthening our testing sometimes by several minutes... I believe this is largely related to JavaFX being slow in creating new stages but also to the default mouse speed that is being used by the robot. One might consider re-using and/or improving upon that in the long run. Large scale UI frameworks would benefit from this.

**Comment by brcolow** [comment]
Merged with #702
