### ISSUE TITLE
OutOfMemoryException by multiple tests - Scene is not cleared in the JavafxRobotAdapter

### ISSUE THREAD

**Issue by j-ferreira** [TestFX/TestFX#709]
When using the write function in the FxRobot class, you will run into an OutOfMemoryExcpetion if you run multiple tests. 

After some heap dump analysis I found out that the scene of the JavaFX application is set in the JavafxRobotAdapter when the write method is called. But the scene remains in the JavafxRobotAdapter even after the test.

For multiple tests, this means that the scene is stored in memory several times. This allows you to run into an OutOfMemoryException. 

In our current project our JavaFX application is about 300MB in memory and we have about 60 tests. Therefore we ran into an OutOfMemoryException sometime. 
Currently we have found a workaround. We create a small stage at the end of each test and on this stage we call the write method to overwrite our actual stage in the JavafxRobotAdapter to free memory.

Additionally I noticed during the analysis in the heap dump that the complete FxRobotContext for each test is kept during the whole runtime. Is this really necessary? 
Although we have found this workaround now, the amount of memory required increases from test to test, because the FxRobotContext is kept for each test even though the test has already run.

If you need an example, I can upload a small example.

## Specifications

  - Version: testfx-4.0.16-alpha
  - Platform: JavaFX 13, AdoptOpenJDK 11, Windows 10

**Comment by brcolow** [comment]
If you have the time and/or motivation to submit a PR it would be super appreciated. We have heard of this issue for quite some time now and it is a real pain point.

**Comment by j-ferreira** [comment]
I'm not really familiar with the architecture of TestFX now, but I can try it. I just found this out over the heap dumps and without background knowledge. 
But what would the target be? That the Scene in the JavafxRobotAdapter is set to null at the end of each test or that the FxRobotContext of the corresponding test is deleted after the test is finished?

I think deleting the FxRobotContext would free up much more memory, but I can't really estimate the effort and I don't know if the FxRobotContext is still needed after the corresponding test?

**Comment by brcolow** [comment]
These are great questions and I think can only really been answered with trial and error. The original author of TestFX is @hastebrot  - he is possibly the only one that could guide you on this work. My contributions have been more geared towards maintenance (and I've done a bad job at that lately).
