### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by patilnikhilh80** [TestFX/TestFX#717]
## Expected Behavior
run the test

## Actual Behavior
java.lang.IllegalAccessError: class org.testfx.toolkit.impl.ToolkitServiceImpl (in module org.testfx) cannot access class com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to module org.testfx

## Specifications
build.gradle
 testImplementation "org.testfx:testfx-core:4.0.15-alpha"
    testImplementation "org.testfx:testfx-junit:4.0.15-alpha"

**Comment by SamTV12345** [comment]
I get the exact same errors lol.

**Comment by SamTV12345** [comment]
@patilnikhilh80 
**Found the fix for our problem:**

https://github.com/TestFX/TestFX/issues/638

Just add this to the plugin section of your pom.xml
` <plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>3.0.0-M5</version>
  <configuration>
    <argLine>
      --add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
    </argLine>
  </configuration>
</plugin>`

**Comment by EachOneChew** [comment]
> @patilnikhilh80 **Found the fix for our problem:**
> 
> #638
> 
> Just add this to the plugin section of your pom.xml ` <plugin> <groupId>org.apache.maven.plugins</groupId> <artifactId>maven-surefire-plugin</artifactId> <version>3.0.0-M5</version> <configuration> <argLine> --add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED </argLine> </configuration> </plugin>`

Is there an equivalent to this for gradle? I have been looking everywhere, without luck.

**Comment by wiverson** [comment]
Any update for this that doesn't require adding the exports line?

**Comment by SamTV12345** [comment]
> Any update for this that doesn't require adding the exports line?
Yes I found a solution. Create a similar structure to your main folder in your test directory and create a module-info.java file in your main java folder. That way the test can access the same resources as your main application. But writing a module info can be also quite frustrating.

**Comment by wiverson** [comment]
Ugh. Been there, done that. I built this https://github.com/wiverson/maven-jpackage-template and https://github.com/wiverson/jtoolprovider-plugin and wrote https://changenode.com/articles/fomo-java-modules and I am sick of fighting Java modules.

Maven surefire command line config it is! Sigh.

**Comment by patilnikhilh80** [comment]
Found solution
