### ISSUE TITLE
Is there a difference between testfx-core and testfx-junit5?

### ISSUE THREAD

**Issue by aubreyyan** [TestFX/TestFX#719]
![image](https://user-images.githubusercontent.com/60039494/109376840-30da3880-7895-11eb-8c61-a4c110a3b230.png)

![image](https://user-images.githubusercontent.com/60039494/109376914-a1815500-7895-11eb-8fb0-26e23dce1cd3.png)

I'm not sure if they're necessarily complementary or the latter is sufficient.

I'm mostly asking because I noticed that testfx-core doesn't provide critical elements like `import org.testfx.framework.junit5.ApplicationExtension;`

**Comment by mvsoder** [comment]
@aubreyyan The latter is sufficient. The testfx-core is a dependency of testfx-junit5 and you should need to specify it yourself. You should only need to specify the testfx-junit5 dependency in your configuration.
