### ISSUE TITLE
Is there support for robot lookup by fxid? If no, why not?

### ISSUE THREAD

**Issue by aubrey-y** [TestFX/TestFX#720]
## Expected Behavior

Almost all relevant testable elements that I've worked on or been exposed to will have fxid's, but not all of them will have css id's. From what I can tell, according to the documentation, there doesn't seem to be support for fxid lookup (say if I wanted to click on a button and wanted to target it by fxid). I'd like to confirm that, and if that is indeed the case, why? Is there some kind of technical constraint or was there some sort of oversight?

## Actual Behavior

![image](https://user-images.githubusercontent.com/60039494/109377373-f4a8d700-7898-11eb-916d-907cee178f67.png)

## Specifications

  - Version:15.0.1
  - Platform: Windows x64

**Comment by Azzurite** [comment]
You can use `lookup(n -> "id".equals(n.getId()))`

**Comment by aubrey-y** [comment]
Great, thanks
