### ISSUE TITLE
Thread-safety when checking properties of nodes

### ISSUE THREAD

**Issue by marcin-chwedczuk** [TestFX/TestFX#727]
Hard to say if this is a bug or not. While playing with TestFX I noticed that matchers often just call an appropriate method on the JavaFX control. For example a matcher for button isCancel assertion may call `Button#isCancelButton()` method.

My concern is that the data for the button is set/changed on JavaFX thread. So we basically have here access to data from multiple threads.

Now I have my own control and I want to create my own matcher. My control contains list of item, pure data. My first attempt was to use `robot.lookup` to find my control node, cast it and get the list via getter. But now I started to worry that this is an unsafe operation (from threading point of view).

What is the advised way to proceed? Should I just ignore threading issues (I haven't experience any real problem so far with this approach), or should I wrap my assertion in `robot.interact(() -> meh())`. What about the build-in assertions?

**Comment by tcfurrer** [comment]
I ran into the exact same question today.

I believe something like the following may be a solution:
```
    waitForAsyncFx(10000, () -> {
        waitFor(10, SECONDS, isFocused(textField));
    }
```

Disclaimer: I have not tested/stressed this enough to make any guarantee!

**Comment by mvsoder** [comment]
@marcin-chwedczuk and @tcfurrer TestFX is generally thread-safe but there is always a way to break it. 
The intended use is that any modifications be done through the FxRobot, which ensures that changes are made on the FX thread. Work done through FxRobot will cause the calling thread to wait for the work to be completed on the FX thread. Asserting node properties from the testing thread should provide consistent results as long as no further modifications are made. 
If external modifications are made on the FX thread, the testing thread should wait by calling WaitForAsyncUtils.waitForFxEvents(), and then assertions can be made.
