### ISSUE TITLE
Question: can TestFX work on application without accessing source code/classes?

### ISSUE THREAD

**Issue by helenzhu618** [TestFX/TestFX#734]
I have a requirement that we want to do UI automation on third party java swing/javafx application. Thus obviously I won't have access to the source code. I've seen heaps of examples using TestFX but all of them seems work with source codes. Instead of looking for more examples/tools, it would be best to get the answer from the source of truth which is here. 
If the answer is yes, could you give me an example? or simply point out which library or dependency I can use in my for example maven project? Thanks.

**Comment by svenruppert** [comment]
Yes you can run it on classes/jars only.
