### ISSUE TITLE
Does TestFX support JavaFX 17 and JDK 17 yet?

### ISSUE THREAD

**Issue by yylonly** [TestFX/TestFX#745]
## Actual Behavior

To get the fastest possible support, create a [minimal example](https://stackoverflow.com/help/mcve)
and upload it to GitHub.

## Specifications

  - Version:
  - Platform:

**Comment by yylonly** [comment]
Seem this repo is dead, I like to make JavaFX support JDK 17 on Apple Silence, any documentation for the contributor?

**Comment by alwins0n** [comment]
@trzimar  are you using a modularized application? I just tried the junit5 extension (latest alpha) with the following result:

```
java.lang.IllegalAccessError: class org.testfx.toolkit.impl.ToolkitServiceImpl (in unnamed module @0x163e4e87) cannot access class com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to unnamed module @0x163e4e87
	org.testfx.toolkit.impl.ToolkitServiceImpl.registerApplicationParameters(ToolkitServiceImpl.java:142)
	org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupApplication$6(ToolkitServiceImpl.java:125)
....
```

**Comment by trzimar** [comment]
@alwins0n non modular and still on JUnit 4

**Comment by mvsoder** [comment]
@alwins0n This particular issue, with access to ParametersImpl may be resolved by https://github.com/TestFX/TestFX/pull/757. TestFX does support JDK9+, but ParametersImpl is still a protected class in JavaFX and we need to workaround that particular issue. If the upcoming release of TestFX 4 does not resolve the issue, you will still need to add the following to your JVM parameters:

```--add-opens=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED```

**Comment by alwins0n** [comment]
thank you. for what it's worth my requirements were really simple and TestFX goes far beyond that.

For my simple project I am happy with this little fellow of mine: https://github.com/alwins0n/fxtension
