### ISSUE TITLE
Cleanup behavior is different between ApplicationTest and ApplicationExtension

### ISSUE THREAD

**Issue by C-Otto** [TestFX/TestFX#748]
I'm using JUnit 5 and run my tests using ApplicationExtension. Due to test failures and some debugging (with some help of [ChatGPT](https://sharegpt.com/c/64KL3Ho), I'm impressed!) I noticed that there's a `@AfterEach` implementation in ApplicationTest. However, there is no corresponding code for `ApplicationExtension` (or `AnnotationBasedApplicationFixture`).

This should either be documented, or fixed in code. As a user of either approaches I expect to be able to switch to the other approach without any relevant change in behavior.

## Specifications

  - Version: 4.0.16-alpha
  - Platform: Gradle 8.0.2, Java 17, org.openjfx.javafxplugin:org.openjfx.javafxplugin.gradle.plugin:0.0.13, JavaFX 19, "javafx.controls" module

**Comment by C-Otto** [comment]
Upon closer investigation, the only difference seems to be hiding all windows. The extension itself registers an `afterEach` method, which runs `FxToolkit.cleanupApplication`.

**Comment by C-Otto** [comment]
Actually, hiding a window seems to be rather important. I still don't fully understand the issues I'm facing, but it seems creating a new maximized stage in test A messes up the click handler in test B. This isn't an issue if I run `FxToolkit.cleanupStages()` in my `@AfterEach`. I'm reopening this issue so that this can be added to `ApplicationExtension`.

**Comment by mvsoder** [comment]
This PR should resolve these differences: https://github.com/TestFX/TestFX/pull/778

**Comment by svenruppert** [comment]
approved and merged for next release
