### ISSUE TITLE
Does repo maintain ?

### ISSUE THREAD

**Issue by enzofrnt** [TestFX/TestFX#750]
Hi, does this repo continue to be maintain?

**Comment by elfoxus** [comment]
Don't think so

**Comment by enzofrnt** [comment]
That is sad… They were doing a freaking job. It still some issue.

**Comment by svenruppert** [comment]
We are working on Version 4 now. Stay tuned :-)

**Comment by enzofrnt** [comment]
Ho nice !

**Comment by svenruppert** [comment]
But it is a longer run.  BTW: If you have any feature ideas..  Open Isues please.

**Comment by enzofrnt** [comment]
If that maintained, I will open an issue because my test aren't working on eclipse 2023-03 on my latest test

**Comment by enzofrnt** [comment]
@svenruppert can we get access to V4 preview ?

**Comment by mvsoder** [comment]
@enzofrnt If you would like a preview, the code should be buildable with JDK 8 as of today. You will note we have the [builds working again](https://github.com/TestFX/TestFX/actions). If you can wait a little longer, we'll get a release available as soon as we curate some bug fixes.
