### ISSUE TITLE
JavaFx 2.2 - Backward Compatibility

### ISSUE THREAD

**Issue by lydiachung** [TestFX/TestFX#86]
I downloaded the latest version and tried to compile against Java 7 + JavaFX 2.2. The BoundsPointQuery class failed to compile because add() and ZERO of Point2D are introduced in JavaFX 8. Will TestFX 3.2 release be backward compatible?

**Comment by brcolow** [comment]
TestFX v4 supports Java 8 and newer. TestFX 3.2 (legacy) is no longer maintained.
